In [3]:
(2025-1182.05)/51.35

16.415774099318405

In [2]:
1182.05/51.35

23.019474196689384

In [4]:
(2025-8948.75)/9.7

-713.7886597938145

In [5]:
import pandas as pd 

mp=pd.read_excel(r"D:\Chrome Download\MARKET PRICE.xlsx")
mp

,Unnamed: 0,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
0,Adani Ports and Special Economic Zone Ltd,1182.05,1341.70,631.80,774.10,702.75,251.30,378.00,354.65,339.80,247.70,308.05,187.50,138.75
1,Asian Paints Ltd,1337.70,2846.00,2761.65,3081.75,2536.75,1666.70,1491.90,1120.70,1071.20,868.70,808.75,546.50,4914.40
2,AXIS Bank Ltd,1101.90,1048.30,858.45,760.65,697.50,379.30,776.10,509.40,490.80,444.55,560.40,1460.45,1301.25
3,Bajaj Finserv Ltd,8948.75,7240.35,5615.40,7259.10,5148.90,2216.05,3024.85,1769.75,1174.10,6929.20,4096.25,1790.05,1154.35
4,Bajaj Finance Ltd,2005.95,1643.65,1266.35,17052.15,9667.80,4589.75,7035.45,5178.55,4087.80,1703.75,1389.45,790.20,769.20
5,Bharat Electronics Ltd,301.20,201.45,97.55,210.85,125.10,74.35,93.30,142.05,156.35,1219.50,3347.25,1144.65,1149.15
6,Bharti Airtel Ltd,1730.95,1229.05,749.00,755.40,517.30,440.60,332.90,398.90,349.95,350.90,393.90,318.90,291.80
7,Eternal Ltd,201.50,182.35,50.96,82.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,HCL Technologies Ltd,1590.95,1543.30,1086.20,1163.35,983.45,436.75,1088.00,969.50,873.05,814.15,979.65,1390.50,795.95
9,HDFC Bank Ltd,1828.50,1448.20,1609.75,1469.95,1493.55,862.00,2316.50,1891.45,1442.30,1071.20,1022.85,748.85,624.10
10,Hindustan Unilever Ltd,2259.35,2268.25,2558.75,2048.85,2430.80,2298.15,1707.80,1335.90,909.75,869.50,872.90,603.65,466.10
11,ICICI Bank Ltd,1348.40,1095.85,877.20,730.25,581.25,324.50,398.85,278.40,277.10,236.55,315.30,1245.45,1045.35
12,Infosys Ltd,1570.40,1498.80,1377.40,1907.20,1367.75,640.30,742.30,1134.40,1020.80,1217.95,2216.60,3278.85,2889.90
13,ITC Ltd,409.80,428.55,383.45,250.80,218.50,172.00,296.70,255.90,280.45,328.05,325.45,352.95,309.10
14,Kotak Mahindra Bank Ltd,2171.30,1785.80,1733.50,1754.70,1754.00,1296.35,1335.75,1048.60,872.10,681.00,1313.15,778.00,651.40
15,Larsen & Toubro Ltd,3491.00,3774.10,2164.75,1767.45,1418.35,806.85,1384.05,1311.90,1577.60,1216.20,1719.00,1272.65,1364.90
16,Mahindra & Mahindra Ltd,2666.35,1921.35,1158.55,805.80,795.10,285.00,671.80,740.20,1284.70,1209.65,1187.15,980.65,861.15
17,Maruti Suzuki India Ltd,11521.45,12613.10,8292.65,7559.90,6859.75,4287.75,6671.70,8863.15,6024.30,3719.10,3699.25,1971.40,1279.70
18,NTPC Ltd,357.65,335.95,175.25,134.95,106.45,84.20,135.35,169.70,165.95,128.80,147.35,119.95,142.00
19,Power Grid Corporation of India Ltd,290.45,277.05,225.70,216.85,215.65,159.00,198.10,193.85,197.20,139.10,145.20,105.05,105.95
20,Reliance Industries Ltd,1275.00,2976.80,2331.05,2633.95,2003.20,1112.45,1363.05,882.80,1319.20,1045.25,824.70,929.50,773.70
21,State Bank of India,771.60,752.60,523.70,493.40,364.35,196.95,320.80,250.10,292.60,194.30,267.00,1918.30,250.10
22,Sun Pharmaceutical Industries Ltd,1735.45,1620.50,983.10,914.80,597.60,352.20,479.25,495.40,687.70,819.45,573.35,573.35,818.35
23,Tata Motors Ltd,674.05,993.00,420.60,433.50,301.85,71.05,174.30,327.45,465.95,386.30,549.95,398.35,269.30
24,Tata Steel Ltd,154.25,155.90,104.50,1307.05,811.95,269.75,520.85,570.90,482.65,319.50,316.85,393.85,312.30
25,Tata Consultancy Services Ltd,3604.45,3883.55,3205.80,3738.80,3177.60,1823.05,2000.40,2849.30,2431.10,2516.05,2547.05,2128.25,1571.80
26,Tech Mahindra Ltd,1418.00,1250.40,1101.85,1499.30,991.25,564.95,776.20,638.30,459.60,475.45,629.45,1794.55,1059.15
27,Titan Company Ltd,3063.80,3804.75,2515.10,2536.15,1557.40,933.50,1137.50,941.20,461.30,338.80,392.00,262.45,256.50
28,Trent Ltd,5311.05,3948.45,1375.10,1276.40,751.50,479.20,359.85,346.15,265.65,1586.05,1468.35,1024.30,994.55
29,UltraTech Cement Ltd,11504.50,9745.05,7620.00,6602.15,6737.30,3254.25,3999.05,3947.85,3989.95,3227.00,2875.00,2188.90,1868.00

In [7]:
mp.shape

(30, 14)

In [12]:
mp=mp.drop(columns=["Unnamed: 0"])
mp

,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
0,1182.05,1341.70,631.80,774.10,702.75,251.30,378.00,354.65,339.80,247.70,308.05,187.50,138.75
1,1337.70,2846.00,2761.65,3081.75,2536.75,1666.70,1491.90,1120.70,1071.20,868.70,808.75,546.50,4914.40
2,1101.90,1048.30,858.45,760.65,697.50,379.30,776.10,509.40,490.80,444.55,560.40,1460.45,1301.25
3,8948.75,7240.35,5615.40,7259.10,5148.90,2216.05,3024.85,1769.75,1174.10,6929.20,4096.25,1790.05,1154.35
4,2005.95,1643.65,1266.35,17052.15,9667.80,4589.75,7035.45,5178.55,4087.80,1703.75,1389.45,790.20,769.20
5,301.20,201.45,97.55,210.85,125.10,74.35,93.30,142.05,156.35,1219.50,3347.25,1144.65,1149.15
6,1730.95,1229.05,749.00,755.40,517.30,440.60,332.90,398.90,349.95,350.90,393.90,318.90,291.80
7,201.50,182.35,50.96,82.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1590.95,1543.30,1086.20,1163.35,983.45,436.75,1088.00,969.50,873.05,814.15,979.65,1390.50,795.95
9,1828.50,1448.20,1609.75,1469.95,1493.55,862.00,2316.50,1891.45,1442.30,1071.20,1022.85,748.85,624.10
10,2259.35,2268.25,2558.75,2048.85,2430.80,2298.15,1707.80,1335.90,909.75,869.50,872.90,603.65,466.10
11,1348.40,1095.85,877.20,730.25,581.25,324.50,398.85,278.40,277.10,236.55,315.30,1245.45,1045.35
12,1570.40,1498.80,1377.40,1907.20,1367.75,640.30,742.30,1134.40,1020.80,1217.95,2216.60,3278.85,2889.90
13,409.80,428.55,383.45,250.80,218.50,172.00,296.70,255.90,280.45,328.05,325.45,352.95,309.10
14,2171.30,1785.80,1733.50,1754.70,1754.00,1296.35,1335.75,1048.60,872.10,681.00,1313.15,778.00,651.40
15,3491.00,3774.10,2164.75,1767.45,1418.35,806.85,1384.05,1311.90,1577.60,1216.20,1719.00,1272.65,1364.90
16,2666.35,1921.35,1158.55,805.80,795.10,285.00,671.80,740.20,1284.70,1209.65,1187.15,980.65,861.15
17,11521.45,12613.10,8292.65,7559.90,6859.75,4287.75,6671.70,8863.15,6024.30,3719.10,3699.25,1971.40,1279.70
18,357.65,335.95,175.25,134.95,106.45,84.20,135.35,169.70,165.95,128.80,147.35,119.95,142.00
19,290.45,277.05,225.70,216.85,215.65,159.00,198.10,193.85,197.20,139.10,145.20,105.05,105.95
20,1275.00,2976.80,2331.05,2633.95,2003.20,1112.45,1363.05,882.80,1319.20,1045.25,824.70,929.50,773.70
21,771.60,752.60,523.70,493.40,364.35,196.95,320.80,250.10,292.60,194.30,267.00,1918.30,250.10
22,1735.45,1620.50,983.10,914.80,597.60,352.20,479.25,495.40,687.70,819.45,573.35,573.35,818.35
23,674.05,993.00,420.60,433.50,301.85,71.05,174.30,327.45,465.95,386.30,549.95,398.35,269.30
24,154.25,155.90,104.50,1307.05,811.95,269.75,520.85,570.90,482.65,319.50,316.85,393.85,312.30
25,3604.45,3883.55,3205.80,3738.80,3177.60,1823.05,2000.40,2849.30,2431.10,2516.05,2547.05,2128.25,1571.80
26,1418.00,1250.40,1101.85,1499.30,991.25,564.95,776.20,638.30,459.60,475.45,629.45,1794.55,1059.15
27,3063.80,3804.75,2515.10,2536.15,1557.40,933.50,1137.50,941.20,461.30,338.80,392.00,262.45,256.50
28,5311.05,3948.45,1375.10,1276.40,751.50,479.20,359.85,346.15,265.65,1586.05,1468.35,1024.30,994.55
29,11504.50,9745.05,7620.00,6602.15,6737.30,3254.25,3999.05,3947.85,3989.95,3227.00,2875.00,2188.90,1868.00

In [14]:
eps=pd.read_excel(r"D:\Chrome Download\DILUTED EPS.xlsx")
eps.shape

(30, 16)

In [15]:
eps=eps.drop(columns=["Unnamed: 0","Unnamed: 1","Unnamed: 2"])

In [16]:
eps

,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
0,51.35,37.55,24.58,22.39,24.58,18.35,19.27,17.74,18.89,13.99,11.18,8.45,7.68
1,38.25,56.94,42.82,31.59,32.73,28.20,22.48,21.26,20.22,18.19,14.54,12.71,116.13
2,90.18,85.01,35.04,45.91,24.19,6.80,19.49,1.86,16.48,34.93,31.23,134.20,120.12
3,9.70,7.30,4.60,26.60,11.20,41.90,19.30,8.90,4.40,10.30,7.90,5.20,3.30
4,268.94,235.98,189.57,115.79,73.00,89.07,68.75,47.05,33.67,238.85,177.70,NaN,NaN
5,7.28,5.45,4.09,9.85,8.62,7.49,7.74,5.83,5.94,5.57,149.65,118.91,113.85
6,56.04,12.80,14.57,7.63,-27.65,-63.41,0.96,2.75,9.51,15.20,11.56,7.01,6.00
7,0.58,0.40,-1.20,-1.67,-1.51,-5.42,-0.03,-3435.77,NaN,NaN,NaN,NaN,NaN
8,64.09,57.86,54.79,49.77,41.07,40.75,73.55,62.19,60.27,39.69,51.79,91.93,57.20
9,92.39,90.01,82.27,68.31,57.61,49.46,82.51,70.76,59.16,50.24,43.60,36.31,28.78
10,45.32,43.74,43.07,37.79,34.03,31.17,27.96,24.08,20.67,19.09,20.16,18.23,17.70
11,71.14,61.96,47.84,35.44,26.83,14.55,6.53,11.89,15.84,17.41,21.17,95.65,83.29
12,64.34,63.39,57.54,52.41,45.52,38.91,35.38,71.00,62.77,59.02,108.26,186.49,165.01
13,27.75,16.38,15.46,12.37,10.70,12.45,10.24,9.20,8.45,7.71,12.00,11.09,9.56
14,111.29,91.45,74.94,60.73,50.49,44.68,37.74,32.66,26.86,18.87,39.40,32.14,29.33
15,109.28,93.88,74.45,61.65,82.41,67.95,63.40,52.49,43.05,45.27,50.98,52.65,84.10
16,115.06,100.70,91.96,58.83,16.15,-1.04,48.70,68.86,33.98,56.49,50.69,75.83,66.76
17,461.20,429.01,271.82,128.43,145.30,187.95,253.26,260.88,248.64,181.98,126.04,94.44,81.74
18,20.34,21.46,17.87,15.66,14.87,11.72,13.88,10.66,13.00,13.10,12.11,13.83,15.27
19,16.69,17.36,22.10,24.12,23.01,21.14,19.18,15.68,14.24,11.39,9.65,9.47,9.32
20,51.47,102.90,98.59,90.85,75.21,63.06,66.80,60.89,101.14,100.75,80.11,76.55,70.65
21,86.91,75.17,62.35,39.64,25.11,22.15,2.58,-5.34,0.31,15.95,22.76,189.85,266.82
22,45.60,39.90,35.30,13.60,12.10,15.70,11.10,9.00,29.00,18.90,18.90,15.20,28.80
23,78.75,81.88,6.29,-29.88,-36.99,-34.88,-84.89,26.45,21.93,34.24,43.43,43.50,30.94
24,2.74,-3.62,7.17,332.09,63.78,11.86,87.74,128.10,-42.89,-6.92,-42.24,35.19,-74.54
25,134.19,125.88,115.19,103.62,86.71,86.19,83.05,134.19,133.41,123.18,101.35,97.67,70.99
26,47.91,26.58,54.76,62.81,50.19,45.85,47.72,42.66,31.64,33.71,26.74,126.78,96.68
27,37.61,39.38,36.61,24.49,10.96,16.91,15.82,12.75,8.17,7.60,9.19,8.28,8.17
28,43.51,41.82,12.51,2.98,-4.11,3.53,2.92,2.62,2.55,1.65,38.92,-5.58,-8.50
29,205.13,242.87,175.54,254.53,189.33,199.49,84.00,80.92,98.88,90.25,76.44,80.42,97.69

In [17]:
new=(mp.keys()-mp)/eps

In [18]:
new

,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
0,16.415774,18.170439,56.598861,55.734703,53.631001,96.386921,85.158277,93.762683,88.787718,126.397427,152.678891,216.153846,244.042969
1,17.968627,-14.436249,-17.250117,-33.547009,-15.757715,12.528369,23.447509,42.206021,46.77547,63.073117,82.960798,115.460268,-24.98407
2,10.236194,11.477473,33.234874,27.474406,54.712691,241.279412,63.771165,811.075269,92.609223,44.988549,46.577009,4.124814,5.925325
3,-713.78866,-714.568493,-780.956522,-196.883459,-279.276786,-4.678998,-52.11658,27.893258,191.568182,-477.009709,-263.449367,43.067308,260.19697
4,0.070834,1.611789,3.991402,-129.805251,-104.750685,-28.850904,-72.966545,-67.174283,-61.502822,1.307306,3.520259,NaN,NaN
5,236.785714,334.412844,470.770171,183.873096,219.941995,259.766355,248.79845,321.7753,313.240741,142.998205,-8.902439,7.310992,7.587615
6,5.247145,62.105469,87.439945,166.002621,-54.383363,-24.907743,1756.354167,588.763636,175.294427,109.546053,140.233564,241.811698,286.866667
7,3143.965517,4604.125,-1643.366667,-1161.497006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,6.772507,8.307985,17.098011,17.252361,25.262966,38.852761,12.658056,16.859624,18.980421,30.280927,19.991311,6.782334,21.277098
9,2.126854,6.397067,5.023095,8.08154,9.155529,23.412859,-3.605624,1.78844,9.714334,18.805732,22.755734,34.843018,48.259208
10,-5.171006,-5.584134,-12.439053,-0.710505,-12.042316,-8.923645,11.130186,28.326412,53.567973,60.057622,56.651786,77.364235,87.39548
11,9.510824,14.979826,23.950669,36.448928,53.661946,116.52921,248.108729,146.307822,109.842172,102.208501,80.288144,8.035024,11.617841
12,7.065589,8.285218,11.220021,2.190422,14.350835,35.458751,36.085359,12.44507,15.870639,13.521688,-1.862184,-6.782401,-5.314223
13,58.205405,97.40232,106.0511,143.185125,168.457944,148.433735,168.193359,191.532609,205.508876,218.929961,140.795833,149.77908,178.232218
14,-1.314584,2.604702,3.86309,4.401449,5.288176,16.196285,18.104134,29.681568,42.624721,70.747218,17.813452,38.456752,46.423457
15,-13.415081,-18.641883,-1.903962,4.128954,7.312826,17.853569,10.014984,13.452086,10.206736,17.667329,5.806199,14.080722,7.706302
16,-5.574048,1.019364,9.400283,20.673126,75.907121,-1668.269231,27.663244,18.556491,21.550912,14.274208,16.331624,13.627192,17.253595
17,-20.590742,-24.682641,-23.065448,-43.119988,-33.301789,-12.065709,-18.371239,-26.238692,-16.116876,-9.358721,-13.362821,0.45108,8.971128
18,81.973943,78.660298,103.399552,120.501277,128.752522,165.170648,135.709654,173.386492,142.388462,144.061069,154.223782,136.952278,122.527832
19,103.927501,100.63076,81.325792,74.840381,78.459365,88.032167,94.937435,116.336097,127.794944,164.784899,193.761658,201.578669,204.619099
20,14.571595,-9.259475,-3.124556,-6.735828,0.236671,14.391849,9.819611,18.643455,6.899347,9.635236,14.85832,14.167211,17.541401
21,14.421816,16.913662,24.046512,38.562059,65.975707,82.30474,658.217054,-331.067416,5562.580645,114.213166,76.801406,0.504082,6.607076
22,6.349781,10.112782,29.458924,81.411765,117.636364,106.229299,138.716216,169.177778,45.837931,63.309524,76.277778,94.779605,41.480903
23,17.154921,12.591597,254.753577,-53.162651,-46.476075,-55.87586,-21.730475,63.914934,70.727314,47.596379,33.733594,37.141379,56.357466
24,682.755474,-516.049724,267.573222,2.15288,18.956569,147.575885,17.07488,11.296643,-35.774073,-245.15896,-40.202415,46.040068,-22.815938
25,-11.770251,-14.772402,-10.268252,-16.56823,-13.338715,2.285068,0.223961,-6.194947,-3.103965,-4.059506,-5.24963,-1.169755,6.21496
26,12.669589,29.10459,16.821585,8.321923,20.517035,31.735005,26.043588,32.341772,49.222503,45.700089,51.815632,1.730951,9.866053
27,-27.620314,-45.219655,-13.441683,-20.994283,42.29927,64.251922,55.720607,84.454902,190.416157,220.684211,176.605005,211.539855,214.99388
28,-75.524017,-46.017456,51.790568,250.201342,-308.880779,436.487252,568.202055,638.110687,686.803922,260.575758,14.045478,-177.365591,-119.817647
29,-46.212158,-31.790876,-31.884471,-17.994539,-24.910474,-6.187027,-23.572024,-23.848863,-19.952973,-13.418283,-11.250654,-2.174832,1.484287

In [23]:
# new is your pandas DataFrame
new.to_excel("new pr.xlsx", index=False)

In [22]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\sinha\anaconda3\envs\env1\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\sinha\anaconda3\envs\env1\lib\site-packages (from openpyxl) (2.0.0)

In [ ]:
import pandas as pd

aa=pd.DataFrame({"Adani_Ports":[62418.24,52915.29,45542.78,38198.82,30547.56,25554.05,24704.08,21234.71,17691.86,13505.49,10767.87,8768.10,6396.27],
                 "Asian Paints Ltd.":[19399.81,18728.30,	15992.23	,13811.56,	12806.29,10130.16,	9470.55	,8410.23,7603.89,	6524.82,4742.36	,4039.22,3384.29],
                 "Axis Bank Ltd":[185433.36,	155511.72,	128740.25,	117495.94,	102980.95,85776.09,	67288.29	,63694.10,	55901.34,	53082.19,44475.49,	37926.20,	32690.42	],
                 "Bajaj Finserv Ltd":[72395.31,	60328.62,	46407.34,	40246.80,	35830.00,31301.25,23740.07,20482.94	,16150.33,13598.50,11089.05	,9495.10,	7975.54	],
                 "Bajaj Finance Ltd.":[96692.87,	76695.35	,54371.98,43712.69,36918.41,32327.63,19697.02,	16545.65,9600.26,	7426.76	,4799.71,0,0],
                 "Bharat Electronics Ltd.":[19973.89,16326.47,	13861.63,12285.93,11059.58,10071.53	,9211.50,	8015.68	,7735.77,	9246.16	,8116.84,	7220.26,6487.49	],
                 "Bharti Airtel Ltd.":[131175.30,	100955.90,	90794.80,	66554.30,	58952.70,77144.80	,71422.20,	69534.40,	67456.30,	66769.30,39777.00,	59756.00,50321.70],
                 "Eternal Ltd.":[30317.00,	20413.00,	19459.80,	16505.50,	7643.79,457.38,	2365.31,	1036.64	,0.00,0.00,0.00,0.00,0.00],
                 "HCL Technologies Ltd.":[69655.00,	68263.00,	65405.00,	61914.00,59913.00,51267.00,	41366.00,	36386.00,	32949.00	,27390.77,24224.39,	19542.18,13158.98],
                 "HDFC Bank Ltd.":[517218.98,	452982.84,	288879.55,	246771.62,	209258.91,175810.38,	153128.00,	109080.11,	91281.44,73798.49,62652.77,43686.82,36166.84],
                 "Hindustan Unilever Ltd.":[49402.00,	51218.00,	50304.00,49061.00,47674.00,8229.00,7867.00	,7281.00,	6744.00	,6573.00,4021.64,	3537.29,2864.77	],
                 "ICICI Bank Ltd.":[306631.95,	250222.56,	209248.29,	177167.61,	153075.71,118518.45	,109889.27,	106310.68,	100395.52,	90123.37,83537.44,	75268.23,	67604.29],
                 "Infosys Ltd.":[95818.00,	88116.00,	75407.00,	75350.00,	76351.00,65450.00,	64948.00,	64923.00,	68,982.00,61744.00,50736.00	,44530.00,	37994.00],
                 "ITC Ltd.":[70030.05,	74507.00,	69155.26,	62455.57,60347.34,65273.26	,59140.87,52510.11,	46412.93,	42679.52,31701.07,	27206.34,	23131.84],"Kotak Mahindra Bank Ltd.":[156400.97,	128898.44,	110760.81,	95641.70,	83345.53,65677.60,	56825.35,	49533.24,	37570.39,	32443.45,21752.09,	18690.85,	14876.49],"Larsen & Toubro Ltd.":[97655.60,	86359.24,	89325.95,	82623.31,	76992.19,68127.25,	62221.60	,55500.23,	50063.32,	44180.36,40909.07,	37711.61,	33859.69	],"Mahindra and Mahindra Ltd.":[77038.86,	66190.55,	56365.79	,47122.64,	41581.92,39969.31	,39983.41	,36775.19	,29737.99,	26492.65,25856.38	,23306.86,	19960.70],"Maruti Suzuki India Ltd.":[96239.90	,85636.00,	61791.30,	55333.50,	52500.60,49413.00	,47092.10,	42559.40	,37075.10,	30616.00,24318.40	,21496.40,	19027.80],"NTPC Ltd.":[184071.16,	160709.27,	147023.17	,135373.74,	125738.47,118839.16,	111356.21,	103563.47,	97838.02,	91575.58,82093.98,	87329.72,	82719.93],"Power Grid Corporation of India Ltd":[92662.81,	87145.11,	83014.51,	76247.13,	69936.07,64695.35,	59088.39,	54425.99,	49865.50,	43969.93	,38438.73,	34697.94,	26403.11],"Reliance Industries Ltd":[843200.00,	793481.00,	715871.00,	779485.00,	700172.00,449166.00	,387112.00,	293491.00,	263705.00,	231548.00,218482.00,	198670.00,	182030.00],"State Bank of India":[458788.68,	386491.06,	330282.60,	281317.72,	251091.75,226405.00,	208949.26,	204581.50,	180800.92,	178442.05	,160640.97,	146623.96,	124348.99],"Sun Pharmaceutical Industries Ltd.":[72218.02,	63666.75,	55995.38,	48011.22,	46462.78,45264.45	,41409.06,	38100.56,	36639.67,	32982.48,25589.71,	18524.95	,14989.73],"Tata Motors Ltd.":[118607.00	,87464.19,	47819.33,	44554.85,	55246.72,63078.53,	60179.56,	95427.91	,58061.89	,78952.41,56261.92,	65603.45,	37637.30],"Tata Steel Ltd.":[91169.63	,92035.76	,103082.10,	114443.04	,73459.99,71301.30,	66650.08,	58595.60,	35544.31,	41457.55,31349.41	,40531.96,	34172.24],"Tata Consultancy Services Ltd.":[94756.00,	90489.00,	90424.00,	89139.00,	86433.00,84126.00	,89446.00,	85128.00,	86214.00	,71072.00,50634.76	,49194.76,	38645.73],"Tech Mahindra Ltd.":[27361.50,	26667.80,	27923.20,	26884.60,	24859.80,21812.30,	20282.40,	18840.40,	16435.20,	14589.50,12248.60,	9180.50	,5425.30],"Titan Company Ltd.":[11624.00,	9393.00,	11851.00,	9303.00,	7497.00,6668.75,	6070.15,	5089.88,	4232.38,	3506.28	,3083.87,	2522.74	,1969.85],"Trent Ltd.":[5461.74,	4067.74	,2595.49,	2364.00,	2313.03,2388.04	,1646.51,	1595.37,	1547.69,	1464.39,1421.96,	990.81,	1238.56	],"UltraTech Cement Ltd.":[70706.21,	60227.47,	54324.54,	50435.27,	44174.68,39043.76,	28362.29,	26381.16,	24391.89,	21,945.63,19,041.18,	17181.90	,15229.59]})


bb=pd.DataFrame({"Adani_Ports":[1149.36,1100.75,1201.75,32.04,26.68,8.23,3.90,4.22,11.01,4.80,292.7,369.02,104.25	],
                 "Asian Paints Ltd.":[257.78,	222.56	,230.70,	218.32,	215.21,180.75	,155.59	,140.12,	146.03,	121.37,119.67	,108.53,	98.57		],"Axis Bank Ltd.":[0,0,0,0,0,0,0,0,0,0,0,0,0],"Bajaj Finserv Ltd":[0.00	,175981.36,	129891.88,	106150.84,	80471.81,71906.21,	62179.91,	65694.72,	32388.46,	30523.60,17,931.01,10300.26	,7360.58],"Bajaj Finance Ltd.":[0.00,	0.00,	0.00,	0.00,	0.00,0.00	,0.00,	45896.31,	33115.96,	25286.86,18273.51,0,0		],"Bharat Electronics Ltd.":[0.00,0.00,	0.00,	0.00,	0.00,0.00,	0.00,	33.33,	16.67,	0.00,0.35,	0.27,	0.22	],"Bharti Airtel Ltd.":[104863.80,	130962.60,	151568.60,	113535.00	,110560.30	,91079.20,	82490.10	,84942.00,	89637.30,	89268.60	,61116.10,	54991.90,	61548.50],"Eternal Ltd.":[0.00	,0.00,	5.80,	0.00,	0.00,1.47	,1.31,	1.33,0.00,0.00,0.00,0.00,0.00		],"HCL Technologies Ltd.":[70.00	,2223.00,	2111.00,	3923.00	,3828.00,2848.00	,2977.00,	338.00	,383.00,	737.40,167.89,	200.64	,796.73		],"HDFC Bank Ltd.":[0,0,0,0,0,0,0,0,0,0,0,0,0],"Hindustan Unilever Ltd.":[0.00,	0.00,	0.00	,0.00,	0.00,	0.00,	0.00,	0.00,	0.00,	0.00	,7.00,	8.44,	8.44	],"ICICI Bank Ltd.":[,0,0,0,0,0,0,0,0,0,0,0,0],"Infosys Ltd.":[0.00,	0.00,	0.00,	0.00,	0.00,0.00,	0.00,	0.00,	0.00,	0.00	,0.00,	0.00,	0.00],"ITC Ltd.":[0.00,	1.76,	3.49	,4.85,	5.58,5.90,	8.15,	11.50,	18.40,	26.66	,39.77	,52.49,	68.28	],"Kotak Mahindra Bank Ltd.":[0,0,0,0,0,0,0,0,0,0,0,0,0],"Larsen & Toubro Ltd.":[57503.34	,56506.97	,61217.68	,61402.66,	80996.38,80927.30	,74120.79,	72914.76	,67340.58,	61223.84	,65277.98,	55447.27,	47400.16],"Mahindra and Mahindra Ltd.":[79707.19	,67719.69,	55027.39	,48625.06,	54906.56,52298.05,	43526.17,	33809.18,	30124.51,	23598.78	,	22327.03,	25491.75,	19860.26],"Maruti Suzuki India Ltd.":[0.00	,0.00,	0.00,	0.00,	2.80,5.40	,8.00,	10.00,	0.00,	0.00,	278.30	,627.40	,704.90		],"NTPC Ltd.":[201053.88,	190214.97	,187883.57	,181,871.19,	181271.91,176020.02,	147063.71,	116775.81,	104075.12	,91205.49,93362.92	,75542.30,	64587.72],"Power Grid Corporation of India Ltd":[109857.95,	105066.95,	113891.29	,114199.40,	129174.79135,421.11	,131329.51,	122710.32,	111253.17	,100463.31	,90492.47,	77772.13,	64030.14],"Reliance Industries Ltd.":[236899.00,	222712.00	,183176.00,	187699.00,	163683.00,197631.00	,207506.00,	144175.00	,152148.00	,141647.00,120777.00,	101016.00,	70960.00],,"State Bank of India":[0,0,0,0,0,0,0,0,0,0,0,0,0],"Sun Pharmaceutical Industries Ltd.":[2.52,	1.33,	0.00	,229.92	,898.13,2028.92	,1522.61,	1772.09,	1436.08	,3110.30,1368.42,	48.67,	115.26],"Tata Motors Ltd":[40217.00	,62148.53	,88695.81	,97759.17,	93112.77, 83315.62	,70817.50	,61199.50	,60629.18	,50510.39,	56071.34,	45258.61,	32110.07	],"Tata Steel Ltd.":[68551.81,	51576.73,	51446.33,	44764.07,	65698.01,94104.97,	80342.73,	72789.10,	64022.27,	64872.78,65675.20	52366.41	46857.62		],"Tata Consultancy Services Ltd.":[0.00,	0.00	,0.00	,0.00,	0.00,0.00,	44.00,	54.00	,71.00	,83.00,114.27	,127.26	,130.98			],"Tech Mahindra Ltd.":[0.00,	102.50,	128.80	,142.00,	165.80	,178.70	,208.60	,771.10	,385.30	,196.60,46.00	,19.00,	300.00],"Titan Company Ltd.":[595.00,	3302.00	,0.00	,2.00,	9.00	,16.97	,31.67,	0.00	,0.00,	0.00,0.00,	0.00,	0.00],"Trent Ltd.":[499.20,	498.56,	497.95,	497.38,	0.00,299.74,	299.56,	99.89,	99.82,	95.98,112.50,	325.00,	325.00],"UltraTech Cement Ltd.":[15780.77,	5307.78,	5356.41,	5303.00,	13548.45,17367.52	,20650.38,	15863.47,	6370.84,	4896.59	,4992.66,6020.76,5169.06		]})

ValueError: All arrays must be of the same length

In [36]:
import pandas as pd

aa = pd.DataFrame({
    "Adani_Ports": [62418.24, 52915.29, 45542.78, 38198.82, 30547.56, 25554.05, 24704.08, 21234.71, 17691.86, 13505.49, 10767.87, 8768.10, 6396.27],
    "Asian Paints Ltd": [19399.81, 18728.30, 15992.23, 13811.56, 12806.29, 10130.16, 9470.55, 8410.23, 7603.89, 6524.82, 4742.36, 4039.22, 3384.29],
    "Axis Bank Ltd": [185433.36, 155511.72, 128740.25, 117495.94, 102980.95, 85776.09, 67288.29, 63694.10, 55901.34, 53082.19, 44475.49, 37926.20, 32690.42],
    "Bajaj Finserv Ltd": [72395.31, 60328.62, 46407.34, 40246.80, 35830.00, 31301.25, 23740.07, 20482.94, 16150.33, 13598.50, 11089.05, 9495.10, 7975.54],
    "Bajaj Finance Ltd": [96692.87, 76695.35, 54371.98, 43712.69, 36918.41, 32327.63, 19697.02, 16545.65, 9600.26, 7426.76, 4799.71, 0, 0],
    "Bharat Electronics Ltd": [19973.89, 16326.47, 13861.63, 12285.93, 11059.58, 10071.53, 9211.50, 8015.68, 7735.77, 9246.16, 8116.84, 7220.26, 6487.49],
    "Bharti Airtel Ltd": [131175.30, 100955.90, 90794.80, 66554.30, 58952.70, 77144.80, 71422.20, 69534.40, 67456.30, 66769.30, 39777.00, 59756.00, 50321.70],
    "Eternal Ltd": [30317.00, 20413.00, 19459.80, 16505.50, 7643.79, 457.38, 2365.31, 1036.64, 0.00, 0.00, 0.00, 0.00, 0.00],
    "HCL Technologies Ltd": [69655.00, 68263.00, 65405.00, 61914.00, 59913.00, 51267.00, 41366.00, 36386.00, 32949.00, 27390.77, 24224.39, 19542.18, 13158.98],
    "HDFC Bank Ltd": [517218.98, 452982.84, 288879.55, 246771.62, 209258.91, 175810.38, 153128.00, 109080.11, 91281.44, 73798.49, 62652.77, 43686.82, 36166.84],
    "Hindustan Unilever Ltd": [49402.00, 51218.00, 50304.00, 49061.00, 47674.00, 8229.00, 7867.00, 7281.00, 6744.00, 6573.00, 4021.64, 3537.29, 2864.77],
    "ICICI Bank Ltd": [306631.95, 250222.56, 209248.29, 177167.61, 153075.71, 118518.45, 109889.27, 106310.68, 100395.52, 90123.37, 83537.44, 75268.23, 67604.29],
    "Infosys Ltd": [95818.00, 88116.00, 75407.00, 75350.00, 76351.00, 65450.00, 64948.00, 64923.00, 68982.00, 61744.00, 50736.00, 44530.00, 37994.00],
    "ITC Ltd": [70030.05, 74507.00, 69155.26, 62455.57, 60347.34, 65273.26, 59140.87, 52510.11, 46412.93, 42679.52, 31701.07, 27206.34, 23131.84],
    "Kotak Mahindra Bank Ltd": [156400.97, 128898.44, 110760.81, 95641.70, 83345.53, 65677.60, 56825.35, 49533.24, 37570.39, 32443.45, 21752.09, 18690.85, 14876.49],
    "Larsen & Toubro Ltd": [97655.60, 86359.24, 89325.95, 82623.31, 76992.19, 68127.25, 62221.60, 55500.23, 50063.32, 44180.36, 40909.07, 37711.61, 33859.69],
    "Mahindra and Mahindra Ltd": [77038.86, 66190.55, 56365.79, 47122.64, 41581.92, 39969.31, 39983.41, 36775.19, 29737.99, 26492.65, 25856.38, 23306.86, 19960.70],
    "Maruti Suzuki India Ltd": [96239.90, 85636.00, 61791.30, 55333.50, 52500.60, 49413.00, 47092.10, 42559.40, 37075.10, 30616.00, 24318.40, 21496.40, 19027.80],
    "NTPC Ltd": [184071.16, 160709.27, 147023.17, 135373.74, 125738.47, 118839.16, 111356.21, 103563.47, 97838.02, 91575.58, 82093.98, 87329.72, 82719.93],
    "Power Grid Corporation of India Ltd": [92662.81, 87145.11, 83014.51, 76247.13, 69936.07, 64695.35, 59088.39, 54425.99, 49865.50, 43969.93, 38438.73, 34697.94, 26403.11],
    "Reliance Industries Ltd": [843200.00, 793481.00, 715871.00, 779485.00, 700172.00, 449166.00, 387112.00, 293491.00, 263705.00, 231548.00, 218482.00, 198670.00, 182030.00],
    "State Bank of India": [458788.68, 386491.06, 330282.60, 281317.72, 251091.75, 226405.00, 208949.26, 204581.50, 180800.92, 178442.05, 160640.97, 146623.96, 124348.99],
    "Sun Pharmaceutical Industries Ltd": [72218.02, 63666.75, 55995.38, 48011.22, 46462.78, 45264.45, 41409.06, 38100.56, 36639.67, 32982.48, 25589.71, 18524.95, 14989.73],
    "Tata Motors Ltd": [118607.00, 87464.19, 47819.33, 44554.85, 55246.72, 63078.53, 60179.56, 95427.91, 58061.89, 78952.41, 56261.92, 65603.45, 37637.30],
    "Tata Steel Ltd": [91169.63, 92035.76, 103082.10, 114443.04, 73459.99, 71301.30, 66650.08, 58595.60, 35544.31, 41457.55, 31349.41, 40531.96, 34172.24],
    "Tata Consultancy Services Ltd": [94756.00, 90489.00, 90424.00, 89139.00, 86433.00, 84126.00, 89446.00, 85128.00, 86214.00, 71072.00, 50634.76, 49194.76, 38645.73],
    "Tech Mahindra Ltd": [27361.50, 26667.80, 27923.20, 26884.60, 24859.80, 21812.30, 20282.40, 18840.40, 16435.20, 14589.50, 12248.60, 9180.50, 5425.30],
    "Titan Company Ltd": [11624.00, 9393.00, 11851.00, 9303.00, 7497.00, 6668.75, 6070.15, 5089.88, 4232.38, 3506.28, 3083.87, 2522.74, 1969.85],
    "Trent Ltd": [5461.74, 4067.74, 2595.49, 2364.00, 2313.03, 2388.04, 1646.51, 1595.37, 1547.69, 1464.39, 1421.96, 990.81, 1238.56],
    "UltraTech Cement Ltd": [70706.21, 60227.47, 54324.54, 50435.27, 44174.68, 39043.76, 28362.29, 26381.16, 24391.89, 21945.63, 19041.18, 17181.90, 15229.59]
})

bb = pd.DataFrame({
    "Adani_Ports": [35681.30,	37525.88,46391.21,	39576.13,32829.70,26084.24,	19717.44,20463.09,17827.36,	15819.67,13849.78,11288.41,10257.50],
    "Asian Paints Ltd": [259.62,54.38,76.15,44.54,14.53,18.63,19.06,28.33,41.07,72.63,78.28	,41.40,47.80],
    "Axis Bank Ltd": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "Bajaj Finserv Ltd": [0.00, 175981.36, 129891.88, 106150.84, 80471.81, 71906.21, 62179.91, 65694.72, 32388.46, 30523.60, 17931.01, 10300.26, 7360.58],
    "Bajaj Finance Ltd": [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 45896.31, 33115.96, 25286.86, 18273.51, 0, 0],
    "Bharat Electronics Ltd": [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 33.33, 16.67, 0.00, 0.35, 0.27, 0.22],
    "Bharti Airtel Ltd": [104863.80, 130962.60, 151568.60, 113535.00, 110560.30, 91079.20, 82490.10, 84942.00, 89637.30, 89268.60, 61116.10, 54991.90, 61548.50],
    "Eternal Ltd": [0.00, 0.00, 5.80, 0.00, 0.00, 1.47, 1.31, 1.33, 0.00, 0.00, 0.00, 0.00, 0.00],
    "HCL Technologies Ltd": [70.00, 2223.00, 2111.00, 3923.00, 3828.00, 2848.00, 2977.00, 338.00, 383.00, 737.40, 167.89, 200.64, 796.73],
    "HDFC Bank Ltd": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "Hindustan Unilever Ltd": [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 7.00, 8.44, 8.44],
    "ICICI Bank Ltd": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "Infosys Ltd": [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],
    "ITC Ltd": [0.00, 1.76, 3.49, 4.85, 5.58, 5.90, 8.15, 11.50, 18.40, 26.66, 39.77, 52.49, 68.28],
    "Kotak Mahindra Bank Ltd": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "Larsen & Toubro Ltd": [57503.34, 56506.97, 61217.68, 61402.66, 80996.38, 80927.30, 74120.79, 72914.76, 67340.58, 61223.84, 65277.98, 55447.27, 47400.16],
    "Mahindra and Mahindra Ltd": [79707.19, 67719.69, 55027.39, 48625.06, 54906.56, 52298.05, 43526.17, 33809.18, 30124.51, 23598.78, 22327.03, 25491.75, 19860.26],
    "Maruti Suzuki India Ltd": [0.00, 0.00, 0.00, 0.00, 2.80, 5.40, 8.00, 10.00, 0.00, 0.00, 278.30, 627.40, 704.90],
    "NTPC Ltd": [201053.88, 190214.97, 187883.57, 181871.19, 181271.91, 176020.02, 147063.71, 116775.81, 104075.12, 91205.49, 93362.92, 75542.30, 64587.72],
    "Power Grid Corporation of India Ltd": [109857.95, 105066.95, 113891.29, 114199.40, 129174.79, 135421.11, 131329.51, 122710.32, 111253.17, 100463.31, 90492.47, 77772.13, 64030.14],
    "Reliance Industries Ltd": [236899.00, 222712.00, 183176.00, 187699.00, 163683.00, 197631.00, 207506.00, 144175.00, 152148.00, 141647.00, 120777.00, 101016.00, 70960.00],
    "State Bank of India": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "Sun Pharmaceutical Industries Ltd": [2.52, 1.33, 0.00, 229.92, 898.13, 2028.92, 1522.61, 1772.09, 1436.08, 3110.30, 1368.42, 48.67, 115.26],
    "Tata Motors Ltd": [40217.00, 62148.53, 88695.81, 97759.17, 93112.77, 83315.62, 70817.50, 61199.50, 60629.18, 50510.39, 56071.34, 45258.61, 32110.07],
    "Tata Steel Ltd": [68551.81, 51576.73, 51446.33, 44764.07, 65698.01, 94104.97, 80342.73, 72789.10, 64022.27, 64872.78, 65675.20, 52366.41, 46857.62],
    "Tata Consultancy Services Ltd": [0, 0, 0, 0, 0, 0, 44.00, 54.00, 71.00, 83.00, 114.27, 127.26, 130.98],
    "Tech Mahindra Ltd": [0.00, 102.50, 128.80, 142.00, 165.80, 178.70, 208.60, 771.10, 385.30, 196.60, 46.00, 19.00, 300.00],
    "Titan Company Ltd": [595.00, 3302.00, 0.00, 2.00, 9.00, 16.97, 31.67, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],
    "Trent Ltd": [499.20, 498.56, 497.95, 497.38, 0.00, 299.74, 299.56, 99.89, 99.82, 95.98, 112.50, 325.00, 325.00],
    "UltraTech Cement Ltd": [15780.77, 5307.78, 5356.41, 5303.00, 13548.45, 17367.52, 20650.38, 15863.47, 6370.84, 4896.59, 4992.66, 6020.76, 5169.06]
})

In [37]:
aa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 30 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Adani_Ports                          13 non-null     float64
 1   Asian Paints Ltd                     13 non-null     float64
 2   Axis Bank Ltd                        13 non-null     float64
 3   Bajaj Finserv Ltd                    13 non-null     float64
 4   Bajaj Finance Ltd                    13 non-null     float64
 5   Bharat Electronics Ltd               13 non-null     float64
 6   Bharti Airtel Ltd                    13 non-null     float64
 7   Eternal Ltd                          13 non-null     float64
 8   HCL Technologies Ltd                 13 non-null     float64
 9   HDFC Bank Ltd                        13 non-null     float64
 10  Hindustan Unilever Ltd               13 non-null     float64
 11  ICICI Bank Ltd                       13 non-null     float64
 12  Infosys Ltd                          13 non-null     float64
 13  ITC Ltd                              13 non-null     float64
 14  Kotak Mahindra Bank Ltd              13 non-null     float64
 15  Larsen & Toubro Ltd                  13 non-null     float64
 16  Mahindra and Mahindra Ltd            13 non-null     float64
 17  Maruti Suzuki India Ltd              13 non-null     float64
 18  NTPC Ltd                             13 non-null     float64
 19  Power Grid Corporation of India Ltd  13 non-null     float64
 20  Reliance Industries Ltd              13 non-null     float64
 21  State Bank of India                  13 non-null     float64
 22  Sun Pharmaceutical Industries Ltd    13 non-null     float64
 23  Tata Motors Ltd                      13 non-null     float64
 24  Tata Steel Ltd                       13 non-null     float64
 25  Tata Consultancy Services Ltd        13 non-null     float64
 26  Tech Mahindra Ltd                    13 non-null     float64
 27  Titan Company Ltd                    13 non-null     float64
 28  Trent Ltd                            13 non-null     float64
 29  UltraTech Cement Ltd                 13 non-null     float64
dtypes: float64(30)
memory usage: 3.2 KB

In [38]:
bb.shape

(13, 30)

In [39]:
aa.shape

(13, 30)

In [40]:
result = bb/ aa
result

,Adani_Ports,Asian Paints Ltd,Axis Bank Ltd,Bajaj Finserv Ltd,Bajaj Finance Ltd,Bharat Electronics Ltd,Bharti Airtel Ltd,Eternal Ltd,HCL Technologies Ltd,HDFC Bank Ltd,...,Reliance Industries Ltd,State Bank of India,Sun Pharmaceutical Industries Ltd,Tata Motors Ltd,Tata Steel Ltd,Tata Consultancy Services Ltd,Tech Mahindra Ltd,Titan Company Ltd,Trent Ltd,UltraTech Cement Ltd
0,0.571649,0.013383,0.0,0.000000,0.000000,0.000000,0.799417,0.000000,0.001005,0.0,...,0.280952,0.0,0.000035,0.339078,0.751915,0.000000,0.000000,0.051187,0.091399,0.223188
1,0.709169,0.002904,0.0,2.917046,0.000000,0.000000,1.297226,0.000000,0.032565,0.0,...,0.280677,0.0,0.000021,0.710560,0.560399,0.000000,0.003844,0.351538,0.122564,0.088129
2,1.018629,0.004762,0.0,2.798951,0.000000,0.000000,1.669353,0.000298,0.032276,0.0,...,0.255879,0.0,0.000000,1.854811,0.499081,0.000000,0.004613,0.000000,0.191852,0.098600
3,1.036056,0.003225,0.0,2.637498,0.000000,0.000000,1.705900,0.000000,0.063362,0.0,...,0.240799,0.0,0.004789,2.194131,0.391147,0.000000,0.005282,0.000215,0.210398,0.105145
4,1.074708,0.001135,0.0,2.245934,0.000000,0.000000,1.875407,0.000000,0.063893,0.0,...,0.233775,0.0,0.019330,1.685399,0.894337,0.000000,0.006669,0.001200,0.000000,0.306702
5,1.020748,0.001839,0.0,2.297231,0.000000,0.000000,1.180627,0.003214,0.055552,0.0,...,0.439995,0.0,0.044824,1.320824,1.319821,0.000000,0.008193,0.002545,0.125517,0.444822
6,0.798145,0.002013,0.0,2.619197,0.000000,0.000000,1.154964,0.000554,0.071967,0.0,...,0.536036,0.0,0.036770,1.176770,1.205441,0.000492,0.010285,0.005217,0.181936,0.728093
7,0.963662,0.003369,0.0,3.207290,2.773920,0.004158,1.221582,0.001283,0.009289,0.0,...,0.491242,0.0,0.046511,0.641317,1.242228,0.000634,0.040928,0.000000,0.062612,0.601318
8,1.007659,0.005401,0.0,2.005436,3.449486,0.002155,1.328820,NaN,0.011624,0.0,...,0.576963,0.0,0.039195,1.044216,1.801196,0.000824,0.023444,0.000000,0.064496,0.261187
9,1.171351,0.011131,0.0,2.244630,3.404831,0.000000,1.336971,NaN,0.026921,0.0,...,0.611739,0.0,0.094302,0.639757,1.564800,0.001168,0.013475,0.000000,0.065543,0.223124
10,1.286214,0.016507,0.0,1.617001,3.807211,0.000043,1.536468,NaN,0.006931,0.0,...,0.552801,0.0,0.053475,0.996613,2.094942,0.002257,0.003756,0.000000,0.079116,0.262203
11,1.287441,0.010250,0.0,1.084797,NaN,0.000037,0.920274,NaN,0.010267,0.0,...,0.508461,0.0,0.002627,0.689882,1.291978,0.002587,0.002070,0.000000,0.328014,0.350413
12,1.603669,0.014124,0.0,0.922894,NaN,0.000034,1.223101,NaN,0.060546,0.0,...,0.389826,0.0,0.007689,0.853145,1.371219,0.003389,0.055296,0.000000,0.262401,0.339409

In [41]:
# Convert aa DataFrame to CSV
aa.to_csv('aa_data.csv', index=False)

# Convert bb DataFrame to CSV
bb.to_csv('bb_data.csv', index=False)

# Convert the division result to CSV
result =bb /aa 
result.to_csv('division_result.csv', index=False)

print("CSV files created successfully!")
print("Files created:")
print("- aa_data.csv")
print("- bb_data.csv")
print("- division_result.csv")

CSV files created successfully!
Files created:
- aa_data.csv
- bb_data.csv
- division_result.csv

In [42]:
result.shape

(13, 30)

In [43]:
result.to_csv("result.csv", index=False)

In [44]:
a=result.T
a

,0,1,2,3,4,5,6,7,8,9,10,11,12
Adani_Ports,0.571649,0.709169,1.018629,1.036056,1.074708,1.020748,0.798145,0.963662,1.007659,1.171351,1.286214,1.287441,1.603669
Asian Paints Ltd,0.013383,0.002904,0.004762,0.003225,0.001135,0.001839,0.002013,0.003369,0.005401,0.011131,0.016507,0.010250,0.014124
Axis Bank Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Bajaj Finserv Ltd,0.000000,2.917046,2.798951,2.637498,2.245934,2.297231,2.619197,3.207290,2.005436,2.244630,1.617001,1.084797,0.922894
Bajaj Finance Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.773920,3.449486,3.404831,3.807211,NaN,NaN
Bharat Electronics Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004158,0.002155,0.000000,0.000043,0.000037,0.000034
Bharti Airtel Ltd,0.799417,1.297226,1.669353,1.705900,1.875407,1.180627,1.154964,1.221582,1.328820,1.336971,1.536468,0.920274,1.223101
Eternal Ltd,0.000000,0.000000,0.000298,0.000000,0.000000,0.003214,0.000554,0.001283,NaN,NaN,NaN,NaN,NaN
HCL Technologies Ltd,0.001005,0.032565,0.032276,0.063362,0.063893,0.055552,0.071967,0.009289,0.011624,0.026921,0.006931,0.010267,0.060546
HDFC Bank Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Hindustan Unilever Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001741,0.002386,0.002946
ICICI Bank Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Infosys Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ITC Ltd,0.000000,0.000024,0.000050,0.000078,0.000092,0.000090,0.000138,0.000219,0.000396,0.000625,0.001255,0.001929,0.002952
Kotak Mahindra Bank Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Larsen & Toubro Ltd,0.588838,0.654325,0.685329,0.743164,1.052008,1.187884,1.191239,1.313774,1.345108,1.385771,1.595685,1.470297,1.399899
Mahindra and Mahindra Ltd,1.034636,1.023102,0.976255,1.031883,1.320443,1.308455,1.088606,0.919348,1.012998,0.890767,0.863502,1.093745,0.994968
Maruti Suzuki India Ltd,0.000000,0.000000,0.000000,0.000000,0.000053,0.000109,0.000170,0.000235,0.000000,0.000000,0.011444,0.029186,0.037046
NTPC Ltd,1.092262,1.183597,1.277918,1.343475,1.441658,1.481162,1.320660,1.127577,1.063749,0.995959,1.137269,0.865024,0.780800
Power Grid Corporation of India Ltd,1.185567,1.205655,1.371944,1.497753,1.847041,2.093212,2.222594,2.254627,2.231065,2.284819,2.354200,2.241405,2.425098
Reliance Industries Ltd,0.280952,0.280677,0.255879,0.240799,0.233775,0.439995,0.536036,0.491242,0.576963,0.611739,0.552801,0.508461,0.389826
State Bank of India,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Sun Pharmaceutical Industries Ltd,0.000035,0.000021,0.000000,0.004789,0.019330,0.044824,0.036770,0.046511,0.039195,0.094302,0.053475,0.002627,0.007689
Tata Motors Ltd,0.339078,0.710560,1.854811,2.194131,1.685399,1.320824,1.176770,0.641317,1.044216,0.639757,0.996613,0.689882,0.853145
Tata Steel Ltd,0.751915,0.560399,0.499081,0.391147,0.894337,1.319821,1.205441,1.242228,1.801196,1.564800,2.094942,1.291978,1.371219
Tata Consultancy Services Ltd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000492,0.000634,0.000824,0.001168,0.002257,0.002587,0.003389
Tech Mahindra Ltd,0.000000,0.003844,0.004613,0.005282,0.006669,0.008193,0.010285,0.040928,0.023444,0.013475,0.003756,0.002070,0.055296
Titan Company Ltd,0.051187,0.351538,0.000000,0.000215,0.001200,0.002545,0.005217,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Trent Ltd,0.091399,0.122564,0.191852,0.210398,0.000000,0.125517,0.181936,0.062612,0.064496,0.065543,0.079116,0.328014,0.262401
UltraTech Cement Ltd,0.223188,0.088129,0.098600,0.105145,0.306702,0.444822,0.728093,0.601318,0.261187,0.223124,0.262203,0.350413,0.339409

In [45]:
a.to_csv('output.csv')

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})


# Transpose
df_T = df.T

print("\nAfter Transpose:")
print(df_T)

Original DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

After Transpose:
   0  1  2
A  1  2  3
B  4  5  6

In [50]:
import pandas as pd
Revenue_From_Operations=pd.DataFrame({"Adani Ports":[30475.33,26710.56,	20617.64,15795.81,12425.50,11201.67,10780.98,11314.75,8427.35,7102.50,6151.98,4823.99,3576.63]
                                      ,"Asian Paints Ltd":[33797.36,35382.12,34367.83,28923.48,21485.20,20048.32,19062.38,16600.58,14872.52,14091.56,14005.33,12581.64,10906.01]
                                      ,"Axis Bank Ltd":[0,0,0,0,0,0,0,0,0,0,0,0,0]
                                      ,"Bajaj Finserv Ltd":[133821.05,110381.91,82071.24,68406.08,60591.20,54346.69,42604.00,32862.37,21149.64,	8563.42,6471.24,4908.01,3821.09]
                                        ,"Bajaj Finance Ltd":[68264.59,53945.36,40288.71,30739.15,26504.52,26223.07,18397.29,12336.56,9258.03,6956.59,5,119.97,0,0]
                                        ,"Bharat Electronics Ltd":[23117.30,19905.49,17404.18,15084.74,13849.71,12636.58,11854.70,10068.72,8336.58,7198.66,6895.32,6335.86,6151.14]
                                        ,"Bharti Airtel Ltd":[172985.20,149982.40,139144.80,116546.90,100615.80,87539.00,80780.20,83687.90,	95468.30,96532.10,96100.70,85746.10,80311.20]
                                        ,"Eternal Ltd":[20243.00,12114.00,7079.40,	4119.60,	1915.75,2398.40,1296.30,466.36,0.00,0.00,0.00,0.00,0.00]
                                        ,"HCL Technologies Ltd":[117055.00,109913.00,101456.00,85651.00,75379.00,70676.00,60427.00,50569.00,47568.00,31135.94,36701.22,32143.66,25581.06]
                                        ,"HDFC Bank Ltd":[0,0,0,0,0,0,0,0,0,0,0,0,0]
                                        ,"Hindustan Unilever Ltd":[62288.00,60966.00,59549.00,51548.00,	46321.00,39238.00,38684.00,34878.00,32464.00,31461.00,31199.72,28538.98,26317.15]
                                        ,"ICICI Bank Ltd":[0,0,0,0,0,0,0,0,0,0,0,0,0]
                                        ,"Infosys Ltd":[162990.00,153670.00,146767.00,121641.00,100472.00,90791.00,82675.00,70522.00,68484.00,62441.00,53319.00,50133.00,40352.00]
                                        ,"ITC Ltd":[74653.32,70315.49,70245.22,60081.36,48952.81,48979.08,47839.00,43122.90,42360.04,38804.19,38433.31,34984.70,31323.45]
                                        ,"Kotak Mahindra Bank Ltd":[0,0,0,0,0,0,0,0,0,0,0,0,0]
                                        ,"Larsen & Toubro Ltd":[254208.65,	221112.91,181661.42,155672.46,134476.75,144308.05,133342.20,117908.12,	107887.53,100034.24,89589.68,84429.34,74498.00	]
                                        ,"Mahindra and Mahindra Ltd":[155645.26,135803.03,119040.38,89353.96,72678.98,74304.07,103015.23,90770.68,82069.37,74762.30,63862.55,66930.97,62643.54]
                                        ,"Maruti Suzuki India Ltd":[145109.90,134921.70,112511.30,83799.80,66571.80,71704.80,83038.50,78117.10,	66924.70,56452.80,49295.00,43271.80,43215.90]
                                        ,"NTPC Ltd":[186144.66,	176641.71,173985.61,132669.28,111267.88,109078.63,	99615.00,	86118.25,	81193.50,	72839.14,80034.89,78538.05,	68891.48]
                                        ,"Power Grid Corporation of India Ltd":[44072.92,44202.75,44005.22,	40784.69,39300.83,36800.13,34831.17,29904.96,25478.82,20576.04,17658.51	,15597.89,13115.50]
                                        ,"Reliance Industries Ltd":[964693.00,901064.00,877835.00,699962.00,466924.00,597535.00,569209.00,391677.00,305382.00,273999.00,375435.00,434460.00,397062.00]
                                        ,"State Bank of India":[0,0,0,0,0,0,0,0,0,0,0,0,0]
                                        ,"Sun Pharmaceutical Industries Ltd":[52041.25,	47758.45,43278.87,	38426.42,	33139.18,32325.17,28686.28,	25992.02,29993.93,27888.07,27286.50,16004.39,11238.89]
                                        ,"Tata Motors Ltd":[436821.00,	434984.12,	342874.58,	275235.23,	246972.17,258594.36,299190.59,288596.09,265498.47,269560.11,260734.33,230677.10,187652.84]
                                        ,"Tata Steel Ltd":[216840.35,	227296.20,	241636.25,	242326.87,154719.28,146106.00,	154691.63,130880.87,111562.05,	105683.18,138318.91,147347.28,133416.60]
                                        ,"Tata Consultancy Services Ltd":[255324.00,240893.00,225458.00,191754.00,164177.00,156949.00,146463.00,123104.00,117966.00,108646.00,94648.41,	81809.36,62989.48]
                                        ,"Tech Mahindra Ltd":[52988.30,	51995.50,53290.20,44646.00,37855.10,36867.70,34742.10,30772.90,29140.80	,26494.20,22621.30,18831.40,6873.10]
                                        ,"Titan Company Ltd":[57143.00,46751.00,37924.00,27417.00,	20088.00,20767.70,19592.06,	15946.49,13186.78,11187.74,11800.99,10826.15,10019.35]
                                        ,"Trent Ltd":[16873.72,12205.31,	8112.33,4417.27,2546.90,3441.31,2585.75,2123.01,1779.99,1540.90,2236.77,2272.32,2017.28	]
                                        ,"UltraTech Cement Ltd":[70857.27,67535.73,	60462.60,49729.38,42677.00,	41780.55,40903.81,30541.18,25091.62,24879.85,24064.75,21443.72,	21156.12]

                                      })

ValueError: All arrays must be of the same length

In [1]:
import pandas as pd

Revenue_From_Operations = pd.DataFrame({
    "Adani Ports": [30475.33,26710.56,20617.64,15795.81,12425.50,11201.67,10780.98,11314.75,8427.35,7102.50,6151.98,4823.99,3576.63],
    "Asian Paints Ltd": [33797.36,35382.12,34367.83,28923.48,21485.20,20048.32,19062.38,16600.58,14872.52,14091.56,14005.33,12581.64,10906.01],
    "Axis Bank Ltd": [0]*13,
    "Bajaj Finserv Ltd": [133821.05,110381.91,82071.24,68406.08,60591.20,54346.69,42604.00,32862.37,21149.64,8563.42,6471.24,4908.01,3821.09],
    "Bajaj Finance Ltd": [68264.59,53945.36,40288.71,30739.15,26504.52,26223.07,18397.29,12336.56,9258.03,6956.59,5119.97,0,0],
    "Bharat Electronics Ltd": [23117.30,19905.49,17404.18,15084.74,13849.71,12636.58,11854.70,10068.72,8336.58,7198.66,6895.32,6335.86,6151.14],
    "Bharti Airtel Ltd": [172985.20,149982.40,139144.80,116546.90,100615.80,87539.00,80780.20,83687.90,95468.30,96532.10,96100.70,85746.10,80311.20],
    "Eternal Ltd": [20243.00,12114.00,7079.40,4119.60,1915.75,2398.40,1296.30,466.36,0,0,0,0,0],
    "HCL Technologies Ltd": [117055.00,109913.00,101456.00,85651.00,75379.00,70676.00,60427.00,50569.00,47568.00,31135.94,36701.22,32143.66,25581.06],
    "HDFC Bank Ltd": [0]*13,
    "Hindustan Unilever Ltd": [62288.00,60966.00,59549.00,51548.00,46321.00,39238.00,38684.00,34878.00,32464.00,31461.00,31199.72,28538.98,26317.15],
    "ICICI Bank Ltd": [0]*13,
    "Infosys Ltd": [162990.00,153670.00,146767.00,121641.00,100472.00,90791.00,82675.00,70522.00,68484.00,62441.00,53319.00,50133.00,40352.00],
    "ITC Ltd": [74653.32,70315.49,70245.22,60081.36,48952.81,48979.08,47839.00,43122.90,42360.04,38804.19,38433.31,34984.70,31323.45],
    "Kotak Mahindra Bank Ltd": [0]*13,
    "Larsen & Toubro Ltd": [254208.65,221112.91,181661.42,155672.46,134476.75,144308.05,133342.20,117908.12,107887.53,100034.24,89589.68,84429.34,74498.00],
    "Mahindra and Mahindra Ltd": [155645.26,135803.03,119040.38,89353.96,72678.98,74304.07,103015.23,90770.68,82069.37,74762.30,63862.55,66930.97,62643.54],
    "Maruti Suzuki India Ltd": [145109.90,134921.70,112511.30,83799.80,66571.80,71704.80,83038.50,78117.10,66924.70,56452.80,49295.00,43271.80,43215.90],
    "NTPC Ltd": [186144.66,176641.71,173985.61,132669.28,111267.88,109078.63,99615.00,86118.25,81193.50,72839.14,80034.89,78538.05,68891.48],
    "Power Grid Corporation of India Ltd": [44072.92,44202.75,44005.22,40784.69,39300.83,36800.13,34831.17,29904.96,25478.82,20576.04,17658.51,15597.89,13115.50],
    "Reliance Industries Ltd": [964693.00,901064.00,877835.00,699962.00,466924.00,597535.00,569209.00,391677.00,305382.00,273999.00,375435.00,434460.00,397062.00],
    "State Bank of India": [0]*13,
    "Sun Pharmaceutical Industries Ltd": [52041.25,47758.45,43278.87,38426.42,33139.18,32325.17,28686.28,25992.02,29993.93,27888.07,27286.50,16004.39,11238.89],
    "Tata Motors Ltd": [436821.00,434984.12,342874.58,275235.23,246972.17,258594.36,299190.59,288596.09,265498.47,269560.11,260734.33,230677.10,187652.84],
    "Tata Steel Ltd": [216840.35,227296.20,241636.25,242326.87,154719.28,146106.00,154691.63,130880.87,111562.05,105683.18,138318.91,147347.28,133416.60],
    "Tata Consultancy Services Ltd": [255324.00,240893.00,225458.00,191754.00,164177.00,156949.00,146463.00,123104.00,117966.00,108646.00,94648.41,81809.36,62989.48],
    "Tech Mahindra Ltd": [52988.30,51995.50,53290.20,44646.00,37855.10,36867.70,34742.10,30772.90,29140.80,26494.20,22621.30,18831.40,6873.10],
    "Titan Company Ltd": [57143.00,46751.00,37924.00,27417.00,20088.00,20767.70,19592.06,15946.49,13186.78,11187.74,11800.99,10826.15,10019.35],
    "Trent Ltd": [16873.72,12205.31,8112.33,4417.27,2546.90,3441.31,2585.75,2123.01,1779.99,1540.90,2236.77,2272.32,2017.28],
    "UltraTech Cement Ltd": [70857.27,67535.73,60462.60,49729.38,42677.00,41780.55,40903.81,30541.18,25091.62,24879.85,24064.75,21443.72,21156.12]
})

Revenue_From_Operations

,Adani Ports,Asian Paints Ltd,Axis Bank Ltd,Bajaj Finserv Ltd,Bajaj Finance Ltd,Bharat Electronics Ltd,Bharti Airtel Ltd,Eternal Ltd,HCL Technologies Ltd,HDFC Bank Ltd,...,Reliance Industries Ltd,State Bank of India,Sun Pharmaceutical Industries Ltd,Tata Motors Ltd,Tata Steel Ltd,Tata Consultancy Services Ltd,Tech Mahindra Ltd,Titan Company Ltd,Trent Ltd,UltraTech Cement Ltd
0,30475.33,33797.36,0,133821.05,68264.59,23117.30,172985.2,20243.00,117055.00,0,...,964693.0,0,52041.25,436821.00,216840.35,255324.00,52988.3,57143.00,16873.72,70857.27
1,26710.56,35382.12,0,110381.91,53945.36,19905.49,149982.4,12114.00,109913.00,0,...,901064.0,0,47758.45,434984.12,227296.20,240893.00,51995.5,46751.00,12205.31,67535.73
2,20617.64,34367.83,0,82071.24,40288.71,17404.18,139144.8,7079.40,101456.00,0,...,877835.0,0,43278.87,342874.58,241636.25,225458.00,53290.2,37924.00,8112.33,60462.60
3,15795.81,28923.48,0,68406.08,30739.15,15084.74,116546.9,4119.60,85651.00,0,...,699962.0,0,38426.42,275235.23,242326.87,191754.00,44646.0,27417.00,4417.27,49729.38
4,12425.50,21485.20,0,60591.20,26504.52,13849.71,100615.8,1915.75,75379.00,0,...,466924.0,0,33139.18,246972.17,154719.28,164177.00,37855.1,20088.00,2546.90,42677.00
5,11201.67,20048.32,0,54346.69,26223.07,12636.58,87539.0,2398.40,70676.00,0,...,597535.0,0,32325.17,258594.36,146106.00,156949.00,36867.7,20767.70,3441.31,41780.55
6,10780.98,19062.38,0,42604.00,18397.29,11854.70,80780.2,1296.30,60427.00,0,...,569209.0,0,28686.28,299190.59,154691.63,146463.00,34742.1,19592.06,2585.75,40903.81
7,11314.75,16600.58,0,32862.37,12336.56,10068.72,83687.9,466.36,50569.00,0,...,391677.0,0,25992.02,288596.09,130880.87,123104.00,30772.9,15946.49,2123.01,30541.18
8,8427.35,14872.52,0,21149.64,9258.03,8336.58,95468.3,0.00,47568.00,0,...,305382.0,0,29993.93,265498.47,111562.05,117966.00,29140.8,13186.78,1779.99,25091.62
9,7102.50,14091.56,0,8563.42,6956.59,7198.66,96532.1,0.00,31135.94,0,...,273999.0,0,27888.07,269560.11,105683.18,108646.00,26494.2,11187.74,1540.90,24879.85
10,6151.98,14005.33,0,6471.24,5119.97,6895.32,96100.7,0.00,36701.22,0,...,375435.0,0,27286.50,260734.33,138318.91,94648.41,22621.3,11800.99,2236.77,24064.75
11,4823.99,12581.64,0,4908.01,0.00,6335.86,85746.1,0.00,32143.66,0,...,434460.0,0,16004.39,230677.10,147347.28,81809.36,18831.4,10826.15,2272.32,21443.72
12,3576.63,10906.01,0,3821.09,0.00,6151.14,80311.2,0.00,25581.06,0,...,397062.0,0,11238.89,187652.84,133416.60,62989.48,6873.1,10019.35,2017.28,21156.12

In [2]:
import pandas as pd

Trade_Receivables = pd.DataFrame({
    "Adani Ports": [4432.36, 3666.94, 3940.79, 2469.68, 2925.71, 3202.14, 2789.66, 3537.91, 1964.76, 2436.09, 1287.77, 1427.56, 728.28],
    "Asian Paints Ltd": [4313.65, 4889.05, 4636.94, 3871.44, 2602.17, 1795.22, 1907.33, 1730.63, 1446.60, 1186.84, 1179.85, 1110.28, 980.88],
    "Axis Bank Ltd": [0]*13,
    "Bajaj Finserv Ltd": [8319.35, 5973.86, 3458.64, 3004.81, 2753.07, 541.45, 370.38, 353.02, 267.08, 177.74, 0.93, 3.11, 0.13],
    "Bajaj Finance Ltd": [1416.39, 1244.89, 1070.21, 1017.11, 720.10, 867.18, 805.38, 34203.92, 25654.78, 0.00, 0.00, 0.00, 0.00],
    "Bharat Electronics Ltd": [9116.37, 7392.38, 7033.48, 6108.09, 6561.99, 6724.02, 5373.67, 5014.30, 4368.26, 3721.91, 3805.32, 4155.88, 3363.56],
    "Bharti Airtel Ltd": [7455.70, 4727.70, 3981.50, 4056.20, 3637.70, 4605.80, 4300.60, 5883.00, 4740.20, 5503.90, 5207.20, 6244.10, 6643.00],
    "Eternal Ltd": [1946.00, 794.00, 456.90, 159.90, 129.87, 123.12, 70.34, 26.08, 0.00, 0.00, 0.00, 0.00, 0.00],
    "HCL Technologies Ltd": [25842.00, 25521.00, 25506.00, 20671.00, 13663.00, 14131.00, 11706.00, 9639.00, 8301.00, 7721.14, 6538.69, 5682.84, 4497.15],
    "HDFC Bank Ltd": [0]*13,
    "Hindustan Unilever Ltd": [3819.00, 2997.00, 3079.00, 2236.00, 1758.00, 1149.00, 1816.00, 1310.00, 1085.00, 1264.00, 1011.18, 1031.09, 996.53],
    "ICICI Bank Ltd": [0]*13,
    "Infosys Ltd": [31158.00, 30193.00, 25424.00, 22698.00, 19294.00, 18487.00, 14827.00, 13142.00, 12322.00, 11330.00, 9713.00, 8351.00, 7083.00],
    "ITC Ltd": [4719.67, 4025.82, 2956.17, 2461.90, 2501.70, 2562.48, 4035.28, 2682.29, 2474.29, 1917.18, 1978.17, 2433.55, 1394.23],
    "Kotak Mahindra Bank Ltd": [0]*13,
    "Larsen & Toubro Ltd": [53713.68, 48770.95, 44731.53, 46138.92, 42229.78, 40731.52, 36845.87, 34654.08, 28688.97, 26024.98, 30089.37, 26384.55, 23014.91],
    "Mahindra and Mahindra Ltd": [8279.70, 7459.40, 7028.02, 6373.95, 6007.76, 6928.28, 9290.51, 8489.82, 7199.26, 5817.60, 5476.16, 5725.42, 5176.97],
    "Maruti Suzuki India Ltd": [6539.70, 4596.80, 3301.40, 2034.50, 1279.90, 1977.70, 2312.80, 1465.40, 1202.60, 1323.40, 1144.30, 1489.10, 1489.20],
    "NTPC Ltd": [34720.30, 33349.68, 28825.22, 27342.08, 17718.07, 20314.59, 12363.52, 8812.19, 8963.89, 8288.79, 9249.92, 6725.66, 6096.64],
    "Power Grid Corporation of India Ltd": [7964.75, 11539.63, 12961.35, 9475.07, 3675.53, 5040.71, 4728.10, 3640.02, 3131.93, 2739.47, 2206.96, 1618.29, 1491.38],
    "Reliance Industries Ltd": [42121.00, 31628.00, 28448.00, 23640.00, 19014.00, 19656.00, 30089.00, 17555.00, 8177.00, 4465.00, 5315.00, 9411.00, 9750.00],
    "State Bank of India": [0]*13,
    "Sun Pharmaceutical Industries Ltd": [13046.11, 11249.37, 11438.51, 10592.89, 9061.40, 9421.24, 8884.20, 7815.28, 7202.61, 6775.66, 5312.32, 2200.42, 2710.77],
    "Tata Motors Ltd": [13248.00, 16951.81, 15737.97, 12442.12, 12679.08, 11172.69, 18996.17, 19893.30, 14075.55, 13570.91, 12579.20, 10574.23, 10942.66],
    "Tata Steel Ltd": [5260.06, 6263.53, 8257.24, 12246.43, 9539.84, 7884.91, 11811.00, 12415.52, 11586.82, 12066.22, 13309.87, 16005.77, 13993.96],
    "Tata Consultancy Services Ltd": [59046.00, 53577.00, 49546.00, 34074.00, 30079.00, 30532.00, 27346.00, 24943.00, 22617.00, 24073.00, 20437.94, 18230.40, 14076.56],
    "Tech Mahindra Ltd": [11547.00, 11401.10, 12881.60, 11933.40, 6472.80, 7577.20, 6958.60, 6497.90, 5337.70, 5770.50, 5205.90, 4348.60, 1703.60],
    "Titan Company Ltd": [1068.00, 1018.00, 674.00, 565.00, 366.00, 311.55, 420.45, 295.69, 207.60, 192.50, 189.73, 154.13, 165.83],
    "Trent Ltd": [62.95, 81.74, 34.39, 17.86, 20.77, 17.12, 16.54, 15.10, 5.92, 12.99, 17.69, 17.17, 24.42],
    "UltraTech Cement Ltd": [5890.25, 4278.16, 3867.02, 3071.61, 2571.73, 2383.22, 2787.03, 2220.63, 1757.09, 1928.21, 1658.82, 1632.06, 1376.29]
})

print("✅ Trade_Receivables DataFrame created successfully!")

✅ Trade_Receivables DataFrame created successfully!

In [3]:
Trade_Receivables

,Adani Ports,Asian Paints Ltd,Axis Bank Ltd,Bajaj Finserv Ltd,Bajaj Finance Ltd,Bharat Electronics Ltd,Bharti Airtel Ltd,Eternal Ltd,HCL Technologies Ltd,HDFC Bank Ltd,...,Reliance Industries Ltd,State Bank of India,Sun Pharmaceutical Industries Ltd,Tata Motors Ltd,Tata Steel Ltd,Tata Consultancy Services Ltd,Tech Mahindra Ltd,Titan Company Ltd,Trent Ltd,UltraTech Cement Ltd
0,4432.36,4313.65,0,8319.35,1416.39,9116.37,7455.7,1946.00,25842.00,0,...,42121.0,0,13046.11,13248.00,5260.06,59046.00,11547.0,1068.00,62.95,5890.25
1,3666.94,4889.05,0,5973.86,1244.89,7392.38,4727.7,794.00,25521.00,0,...,31628.0,0,11249.37,16951.81,6263.53,53577.00,11401.1,1018.00,81.74,4278.16
2,3940.79,4636.94,0,3458.64,1070.21,7033.48,3981.5,456.90,25506.00,0,...,28448.0,0,11438.51,15737.97,8257.24,49546.00,12881.6,674.00,34.39,3867.02
3,2469.68,3871.44,0,3004.81,1017.11,6108.09,4056.2,159.90,20671.00,0,...,23640.0,0,10592.89,12442.12,12246.43,34074.00,11933.4,565.00,17.86,3071.61
4,2925.71,2602.17,0,2753.07,720.10,6561.99,3637.7,129.87,13663.00,0,...,19014.0,0,9061.40,12679.08,9539.84,30079.00,6472.8,366.00,20.77,2571.73
5,3202.14,1795.22,0,541.45,867.18,6724.02,4605.8,123.12,14131.00,0,...,19656.0,0,9421.24,11172.69,7884.91,30532.00,7577.2,311.55,17.12,2383.22
6,2789.66,1907.33,0,370.38,805.38,5373.67,4300.6,70.34,11706.00,0,...,30089.0,0,8884.20,18996.17,11811.00,27346.00,6958.6,420.45,16.54,2787.03
7,3537.91,1730.63,0,353.02,34203.92,5014.30,5883.0,26.08,9639.00,0,...,17555.0,0,7815.28,19893.30,12415.52,24943.00,6497.9,295.69,15.10,2220.63
8,1964.76,1446.60,0,267.08,25654.78,4368.26,4740.2,0.00,8301.00,0,...,8177.0,0,7202.61,14075.55,11586.82,22617.00,5337.7,207.60,5.92,1757.09
9,2436.09,1186.84,0,177.74,0.00,3721.91,5503.9,0.00,7721.14,0,...,4465.0,0,6775.66,13570.91,12066.22,24073.00,5770.5,192.50,12.99,1928.21
10,1287.77,1179.85,0,0.93,0.00,3805.32,5207.2,0.00,6538.69,0,...,5315.0,0,5312.32,12579.20,13309.87,20437.94,5205.9,189.73,17.69,1658.82
11,1427.56,1110.28,0,3.11,0.00,4155.88,6244.1,0.00,5682.84,0,...,9411.0,0,2200.42,10574.23,16005.77,18230.40,4348.6,154.13,17.17,1632.06
12,728.28,980.88,0,0.13,0.00,3363.56,6643.0,0.00,4497.15,0,...,9750.0,0,2710.77,10942.66,13993.96,14076.56,1703.6,165.83,24.42,1376.29

In [4]:
tr=Trade_Receivables.transpose()
tr

,0,1,2,3,4,5,6,7,8,9,10,11,12
Adani Ports,4432.36,3666.94,3940.79,2469.68,2925.71,3202.14,2789.66,3537.91,1964.76,2436.09,1287.77,1427.56,728.28
Asian Paints Ltd,4313.65,4889.05,4636.94,3871.44,2602.17,1795.22,1907.33,1730.63,1446.60,1186.84,1179.85,1110.28,980.88
Axis Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Bajaj Finserv Ltd,8319.35,5973.86,3458.64,3004.81,2753.07,541.45,370.38,353.02,267.08,177.74,0.93,3.11,0.13
Bajaj Finance Ltd,1416.39,1244.89,1070.21,1017.11,720.10,867.18,805.38,34203.92,25654.78,0.00,0.00,0.00,0.00
Bharat Electronics Ltd,9116.37,7392.38,7033.48,6108.09,6561.99,6724.02,5373.67,5014.30,4368.26,3721.91,3805.32,4155.88,3363.56
Bharti Airtel Ltd,7455.70,4727.70,3981.50,4056.20,3637.70,4605.80,4300.60,5883.00,4740.20,5503.90,5207.20,6244.10,6643.00
Eternal Ltd,1946.00,794.00,456.90,159.90,129.87,123.12,70.34,26.08,0.00,0.00,0.00,0.00,0.00
HCL Technologies Ltd,25842.00,25521.00,25506.00,20671.00,13663.00,14131.00,11706.00,9639.00,8301.00,7721.14,6538.69,5682.84,4497.15
HDFC Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Hindustan Unilever Ltd,3819.00,2997.00,3079.00,2236.00,1758.00,1149.00,1816.00,1310.00,1085.00,1264.00,1011.18,1031.09,996.53
ICICI Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Infosys Ltd,31158.00,30193.00,25424.00,22698.00,19294.00,18487.00,14827.00,13142.00,12322.00,11330.00,9713.00,8351.00,7083.00
ITC Ltd,4719.67,4025.82,2956.17,2461.90,2501.70,2562.48,4035.28,2682.29,2474.29,1917.18,1978.17,2433.55,1394.23
Kotak Mahindra Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Larsen & Toubro Ltd,53713.68,48770.95,44731.53,46138.92,42229.78,40731.52,36845.87,34654.08,28688.97,26024.98,30089.37,26384.55,23014.91
Mahindra and Mahindra Ltd,8279.70,7459.40,7028.02,6373.95,6007.76,6928.28,9290.51,8489.82,7199.26,5817.60,5476.16,5725.42,5176.97
Maruti Suzuki India Ltd,6539.70,4596.80,3301.40,2034.50,1279.90,1977.70,2312.80,1465.40,1202.60,1323.40,1144.30,1489.10,1489.20
NTPC Ltd,34720.30,33349.68,28825.22,27342.08,17718.07,20314.59,12363.52,8812.19,8963.89,8288.79,9249.92,6725.66,6096.64
Power Grid Corporation of India Ltd,7964.75,11539.63,12961.35,9475.07,3675.53,5040.71,4728.10,3640.02,3131.93,2739.47,2206.96,1618.29,1491.38
Reliance Industries Ltd,42121.00,31628.00,28448.00,23640.00,19014.00,19656.00,30089.00,17555.00,8177.00,4465.00,5315.00,9411.00,9750.00
State Bank of India,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Sun Pharmaceutical Industries Ltd,13046.11,11249.37,11438.51,10592.89,9061.40,9421.24,8884.20,7815.28,7202.61,6775.66,5312.32,2200.42,2710.77
Tata Motors Ltd,13248.00,16951.81,15737.97,12442.12,12679.08,11172.69,18996.17,19893.30,14075.55,13570.91,12579.20,10574.23,10942.66
Tata Steel Ltd,5260.06,6263.53,8257.24,12246.43,9539.84,7884.91,11811.00,12415.52,11586.82,12066.22,13309.87,16005.77,13993.96
Tata Consultancy Services Ltd,59046.00,53577.00,49546.00,34074.00,30079.00,30532.00,27346.00,24943.00,22617.00,24073.00,20437.94,18230.40,14076.56
Tech Mahindra Ltd,11547.00,11401.10,12881.60,11933.40,6472.80,7577.20,6958.60,6497.90,5337.70,5770.50,5205.90,4348.60,1703.60
Titan Company Ltd,1068.00,1018.00,674.00,565.00,366.00,311.55,420.45,295.69,207.60,192.50,189.73,154.13,165.83
Trent Ltd,62.95,81.74,34.39,17.86,20.77,17.12,16.54,15.10,5.92,12.99,17.69,17.17,24.42
UltraTech Cement Ltd,5890.25,4278.16,3867.02,3071.61,2571.73,2383.22,2787.03,2220.63,1757.09,1928.21,1658.82,1632.06,1376.29

In [5]:
tr.rename(columns={0:'2025',1:'2024',2:'2023',3:'2022',4:'2021',5:'2020',6:'2019',7:'2018',8:'2017',9:'2016',10:'2015',11:'2014',12:'2013'},inplace=True)
tr

,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
Adani Ports,4432.36,3666.94,3940.79,2469.68,2925.71,3202.14,2789.66,3537.91,1964.76,2436.09,1287.77,1427.56,728.28
Asian Paints Ltd,4313.65,4889.05,4636.94,3871.44,2602.17,1795.22,1907.33,1730.63,1446.60,1186.84,1179.85,1110.28,980.88
Axis Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Bajaj Finserv Ltd,8319.35,5973.86,3458.64,3004.81,2753.07,541.45,370.38,353.02,267.08,177.74,0.93,3.11,0.13
Bajaj Finance Ltd,1416.39,1244.89,1070.21,1017.11,720.10,867.18,805.38,34203.92,25654.78,0.00,0.00,0.00,0.00
Bharat Electronics Ltd,9116.37,7392.38,7033.48,6108.09,6561.99,6724.02,5373.67,5014.30,4368.26,3721.91,3805.32,4155.88,3363.56
Bharti Airtel Ltd,7455.70,4727.70,3981.50,4056.20,3637.70,4605.80,4300.60,5883.00,4740.20,5503.90,5207.20,6244.10,6643.00
Eternal Ltd,1946.00,794.00,456.90,159.90,129.87,123.12,70.34,26.08,0.00,0.00,0.00,0.00,0.00
HCL Technologies Ltd,25842.00,25521.00,25506.00,20671.00,13663.00,14131.00,11706.00,9639.00,8301.00,7721.14,6538.69,5682.84,4497.15
HDFC Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Hindustan Unilever Ltd,3819.00,2997.00,3079.00,2236.00,1758.00,1149.00,1816.00,1310.00,1085.00,1264.00,1011.18,1031.09,996.53
ICICI Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Infosys Ltd,31158.00,30193.00,25424.00,22698.00,19294.00,18487.00,14827.00,13142.00,12322.00,11330.00,9713.00,8351.00,7083.00
ITC Ltd,4719.67,4025.82,2956.17,2461.90,2501.70,2562.48,4035.28,2682.29,2474.29,1917.18,1978.17,2433.55,1394.23
Kotak Mahindra Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Larsen & Toubro Ltd,53713.68,48770.95,44731.53,46138.92,42229.78,40731.52,36845.87,34654.08,28688.97,26024.98,30089.37,26384.55,23014.91
Mahindra and Mahindra Ltd,8279.70,7459.40,7028.02,6373.95,6007.76,6928.28,9290.51,8489.82,7199.26,5817.60,5476.16,5725.42,5176.97
Maruti Suzuki India Ltd,6539.70,4596.80,3301.40,2034.50,1279.90,1977.70,2312.80,1465.40,1202.60,1323.40,1144.30,1489.10,1489.20
NTPC Ltd,34720.30,33349.68,28825.22,27342.08,17718.07,20314.59,12363.52,8812.19,8963.89,8288.79,9249.92,6725.66,6096.64
Power Grid Corporation of India Ltd,7964.75,11539.63,12961.35,9475.07,3675.53,5040.71,4728.10,3640.02,3131.93,2739.47,2206.96,1618.29,1491.38
Reliance Industries Ltd,42121.00,31628.00,28448.00,23640.00,19014.00,19656.00,30089.00,17555.00,8177.00,4465.00,5315.00,9411.00,9750.00
State Bank of India,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Sun Pharmaceutical Industries Ltd,13046.11,11249.37,11438.51,10592.89,9061.40,9421.24,8884.20,7815.28,7202.61,6775.66,5312.32,2200.42,2710.77
Tata Motors Ltd,13248.00,16951.81,15737.97,12442.12,12679.08,11172.69,18996.17,19893.30,14075.55,13570.91,12579.20,10574.23,10942.66
Tata Steel Ltd,5260.06,6263.53,8257.24,12246.43,9539.84,7884.91,11811.00,12415.52,11586.82,12066.22,13309.87,16005.77,13993.96
Tata Consultancy Services Ltd,59046.00,53577.00,49546.00,34074.00,30079.00,30532.00,27346.00,24943.00,22617.00,24073.00,20437.94,18230.40,14076.56
Tech Mahindra Ltd,11547.00,11401.10,12881.60,11933.40,6472.80,7577.20,6958.60,6497.90,5337.70,5770.50,5205.90,4348.60,1703.60
Titan Company Ltd,1068.00,1018.00,674.00,565.00,366.00,311.55,420.45,295.69,207.60,192.50,189.73,154.13,165.83
Trent Ltd,62.95,81.74,34.39,17.86,20.77,17.12,16.54,15.10,5.92,12.99,17.69,17.17,24.42
UltraTech Cement Ltd,5890.25,4278.16,3867.02,3071.61,2571.73,2383.22,2787.03,2220.63,1757.09,1928.21,1658.82,1632.06,1376.29

In [ ]:
import pandas as pd

Trade_Receivables = pd.DataFrame({
    "Adani Ports": [4432.36, 3666.94, 3940.79, 2469.68, 2925.71, 3202.14, 2789.66, 3537.91, 1964.76, 2436.09, 1287.77, 1427.56, 728.28],
    "Asian Paints Ltd": [4313.65, 4889.05, 4636.94, 3871.44, 2602.17, 1795.22, 1907.33, 1730.63, 1446.60, 1186.84, 1179.85, 1110.28, 980.88],
    "Axis Bank Ltd": [0]*13,
    "Bajaj Finserv Ltd": [8319.35, 5973.86, 3458.64, 3004.81, 2753.07, 541.45, 370.38, 353.02, 267.08, 177.74, 0.93, 3.11, 0.13],
    "Bajaj Finance Ltd": [1416.39, 1244.89, 1070.21, 1017.11, 720.10, 867.18, 805.38, 34203.92, 25654.78, 0.00, 0.00, 0.00, 0.00],
    "Bharat Electronics Ltd": [9116.37, 7392.38, 7033.48, 6108.09, 6561.99, 6724.02, 5373.67, 5014.30, 4368.26, 3721.91, 3805.32, 4155.88, 3363.56],
    "Bharti Airtel Ltd": [7455.70, 4727.70, 3981.50, 4056.20, 3637.70, 4605.80, 4300.60, 5883.00, 4740.20, 5503.90, 5207.20, 6244.10, 6643.00],
    "Eternal Ltd": [1946.00, 794.00, 456.90, 159.90, 129.87, 123.12, 70.34, 26.08, 0.00, 0.00, 0.00, 0.00, 0.00],
    "HCL Technologies Ltd": [25842.00, 25521.00, 25506.00, 20671.00, 13663.00, 14131.00, 11706.00, 9639.00, 8301.00, 7721.14, 6538.69, 5682.84, 4497.15],
    "HDFC Bank Ltd": [0]*13,
    "Hindustan Unilever Ltd": [3819.00, 2997.00, 3079.00, 2236.00, 1758.00, 1149.00, 1816.00, 1310.00, 1085.00, 1264.00, 1011.18, 1031.09, 996.53],
    "ICICI Bank Ltd": [0]*13,
    "Infosys Ltd": [31158.00, 30193.00, 25424.00, 22698.00, 19294.00, 18487.00, 14827.00, 13142.00, 12322.00, 11330.00, 9713.00, 8351.00, 7083.00],
    "ITC Ltd": [4719.67, 4025.82, 2956.17, 2461.90, 2501.70, 2562.48, 4035.28, 2682.29, 2474.29, 1917.18, 1978.17, 2433.55, 1394.23],
    "Kotak Mahindra Bank Ltd": [0]*13,
    "Larsen & Toubro Ltd": [53713.68, 48770.95, 44731.53, 46138.92, 42229.78, 40731.52, 36845.87, 34654.08, 28688.97, 26024.98, 30089.37, 26384.55, 23014.91],
    "Mahindra and Mahindra Ltd": [8279.70, 7459.40, 7028.02, 6373.95, 6007.76, 6928.28, 9290.51, 8489.82, 7199.26, 5817.60, 5476.16, 5725.42, 5176.97],
    "Maruti Suzuki India Ltd": [6539.70, 4596.80, 3301.40, 2034.50, 1279.90, 1977.70, 2312.80, 1465.40, 1202.60, 1323.40, 1144.30, 1489.10, 1489.20],
    "NTPC Ltd": [34720.30, 33349.68, 28825.22, 27342.08, 17718.07, 20314.59, 12363.52, 8812.19, 8963.89, 8288.79, 9249.92, 6725.66, 6096.64],
    "Power Grid Corporation of India Ltd": [7964.75, 11539.63, 12961.35, 9475.07, 3675.53, 5040.71, 4728.10, 3640.02, 3131.93, 2739.47, 2206.96, 1618.29, 1491.38],
    "Reliance Industries Ltd": [42121.00, 31628.00, 28448.00, 23640.00, 19014.00, 19656.00, 30089.00, 17555.00, 8177.00, 4465.00, 5315.00, 9411.00, 9750.00],
    "State Bank of India": [0]*13,
    "Sun Pharmaceutical Industries Ltd": [13046.11, 11249.37, 11438.51, 10592.89, 9061.40, 9421.24, 8884.20, 7815.28, 7202.61, 6775.66, 5312.32, 2200.42, 2710.77],
    "Tata Motors Ltd": [13248.00, 16951.81, 15737.97, 12442.12, 12679.08, 11172.69, 18996.17, 19893.30, 14075.55, 13570.91, 12579.20, 10574.23, 10942.66],
    "Tata Steel Ltd": [5260.06, 6263.53, 8257.24, 12246.43, 9539.84, 7884.91, 11811.00, 12415.52, 11586.82, 12066.22, 13309.87, 16005.77, 13993.96],
    "Tata Consultancy Services Ltd": [59046.00, 53577.00, 49546.00, 34074.00, 30079.00, 30532.00, 27346.00, 24943.00, 22617.00, 24073.00, 20437.94, 18230.40, 14076.56],
    "Tech Mahindra Ltd": [11547.00, 11401.10, 12881.60, 11933.40, 6472.80, 7577.20, 6958.60, 6497.90, 5337.70, 5770.50, 5205.90, 4348.60, 1703.60],
    "Titan Company Ltd": [1068.00, 1018.00, 674.00, 565.00, 366.00, 311.55, 420.45, 295.69, 207.60, 192.50, 189.73, 154.13, 165.83],
    "Trent Ltd": [62.95, 81.74, 34.39, 17.86, 20.77, 17.12, 16.54, 15.10, 5.92, 12.99, 17.69, 17.17, 24.42],
    "UltraTech Cement Ltd": [5890.25, 4278.16, 3867.02, 3071.61, 2571.73, 2383.22, 2787.03, 2220.63, 1757.09, 1928.21, 1658.82, 1632.06, 1376.29]
})

Original Trade Receivables Data:
                                         2025      2024      2023      2022  \
Adani Ports                           4432.36   3666.94   3940.79   2469.68
Asian Paints Ltd                      4313.65   4889.05   4636.94   3871.44
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                     8319.35   5973.86   3458.64   3004.81
Bajaj Finance Ltd                     1416.39   1244.89   1070.21   1017.11
Bharat Electronics Ltd                9116.37   7392.38   7033.48   6108.09
Bharti Airtel Ltd                     7455.70   4727.70   3981.50   4056.20
Eternal Ltd                           1946.00    794.00    456.90    159.90
HCL Technologies Ltd                 25842.00  25521.00  25506.00  20671.00
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                3819.00   2997.00   3079.00   2236.00
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          31158.00  30193.00  25424.00  22698.00
ITC Ltd                               4719.67   4025.82   2956.17   2461.90
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  53713.68  48770.95  44731.53  46138.92
Mahindra and Mahindra Ltd             8279.70   7459.40   7028.02   6373.95
Maruti Suzuki India Ltd               6539.70   4596.80   3301.40   2034.50
NTPC Ltd                             34720.30  33349.68  28825.22  27342.08
Power Grid Corporation of India Ltd   7964.75  11539.63  12961.35   9475.07
Reliance Industries Ltd              42121.00  31628.00  28448.00  23640.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd    13046.11  11249.37  11438.51  10592.89
Tata Motors Ltd                      13248.00  16951.81  15737.97  12442.12
Tata Steel Ltd                        5260.06   6263.53   8257.24  12246.43
Tata Consultancy Services Ltd        59046.00  53577.00  49546.00  34074.00
Tech Mahindra Ltd                    11547.00  11401.10  12881.60  11933.40
Titan Company Ltd                     1068.00   1018.00    674.00    565.00
Trent Ltd                               62.95     81.74     34.39     17.86
UltraTech Cement Ltd                  5890.25   4278.16   3867.02   3071.61

                                         2021      2020      2019      2018  \
Adani Ports                           2925.71   3202.14   2789.66   3537.91
Asian Paints Ltd                      2602.17   1795.22   1907.33   1730.63
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                     2753.07    541.45    370.38    353.02
Bajaj Finance Ltd                      720.10    867.18    805.38  34203.92
Bharat Electronics Ltd                6561.99   6724.02   5373.67   5014.30
Bharti Airtel Ltd                     3637.70   4605.80   4300.60   5883.00
Eternal Ltd                            129.87    123.12     70.34     26.08
HCL Technologies Ltd                 13663.00  14131.00  11706.00   9639.00
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                1758.00   1149.00   1816.00   1310.00
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          19294.00  18487.00  14827.00  13142.00
ITC Ltd                               2501.70   2562.48   4035.28   2682.29
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  42229.78  40731.52  36845.87  34654.08
Mahindra and Mahindra Ltd             6007.76   6928.28   9290.51   8489.82
Maruti Suzuki India Ltd               1279.90   1977.70   2312.80   1465.40
NTPC Ltd                             17718.07  20314.59  12363.52   8812.19
Power Grid Corporation of India Ltd   3675.53   5040.71   4728.10   3640.02
Reliance Industries Ltd              19014.00  19656.00  30089.00  17555.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd     9061.40   9421.24   8884.20   7815.28
Tata Motors Ltd                      12679.08  11172.69  18996.17  19893.30
Tata Steel Ltd                        9539.84   7884.91  11811.00  12415.52
Tata Consultancy Services Ltd        30079.00  30532.00  27346.00  24943.00
Tech Mahindra Ltd                     6472.80   7577.20   6958.60   6497.90
Titan Company Ltd                      366.00    311.55    420.45    295.69
Trent Ltd                               20.77     17.12     16.54     15.10
UltraTech Cement Ltd                  2571.73   2383.22   2787.03   2220.63

                                         2017      2016      2015      2014  \
Adani Ports                           1964.76   2436.09   1287.77   1427.56
Asian Paints Ltd                      1446.60   1186.84   1179.85   1110.28
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                      267.08    177.74      0.93      3.11
Bajaj Finance Ltd                    25654.78      0.00      0.00      0.00
Bharat Electronics Ltd                4368.26   3721.91   3805.32   4155.88
Bharti Airtel Ltd                     4740.20   5503.90   5207.20   6244.10
Eternal Ltd                              0.00      0.00      0.00      0.00
HCL Technologies Ltd                  8301.00   7721.14   6538.69   5682.84
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                1085.00   1264.00   1011.18   1031.09
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          12322.00  11330.00   9713.00   8351.00
ITC Ltd                               2474.29   1917.18   1978.17   2433.55
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  28688.97  26024.98  30089.37  26384.55
Mahindra and Mahindra Ltd             7199.26   5817.60   5476.16   5725.42
Maruti Suzuki India Ltd               1202.60   1323.40   1144.30   1489.10
NTPC Ltd                              8963.89   8288.79   9249.92   6725.66
Power Grid Corporation of India Ltd   3131.93   2739.47   2206.96   1618.29
Reliance Industries Ltd               8177.00   4465.00   5315.00   9411.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd     7202.61   6775.66   5312.32   2200.42
Tata Motors Ltd                      14075.55  13570.91  12579.20  10574.23
Tata Steel Ltd                       11586.82  12066.22  13309.87  16005.77
Tata Consultancy Services Ltd        22617.00  24073.00  20437.94  18230.40
Tech Mahindra Ltd                     5337.70   5770.50   5205.90   4348.60
Titan Company Ltd                      207.60    192.50    189.73    154.13
Trent Ltd                                5.92     12.99     17.69     17.17
UltraTech Cement Ltd                  1757.09   1928.21   1658.82   1632.06

                                         2013
Adani Ports                            728.28
Asian Paints Ltd                       980.88
Axis Bank Ltd                            0.00
Bajaj Finserv Ltd                        0.13
Bajaj Finance Ltd                        0.00
Bharat Electronics Ltd                3363.56
Bharti Airtel Ltd                     6643.00
Eternal Ltd                              0.00
HCL Technologies Ltd                  4497.15
HDFC Bank Ltd                            0.00
Hindustan Unilever Ltd                 996.53
ICICI Bank Ltd                           0.00
Infosys Ltd                           7083.00
ITC Ltd                               1394.23
Kotak Mahindra Bank Ltd                  0.00
Larsen & Toubro Ltd                  23014.91
Mahindra and Mahindra Ltd             5176.97
Maruti Suzuki India Ltd               1489.20
NTPC Ltd                              6096.64
Power Grid Corporation of India Ltd   1491.38
Reliance Industries Ltd               9750.00
State Bank of India                      0.00
Sun Pharmaceutical Industries Ltd     2710.77
Tata Motors Ltd                      10942.66
Tata Steel Ltd                       13993.96
Tata Consultancy Services Ltd        14076.56
Tech Mahindra Ltd                     1703.60
Titan Company Ltd                      165.83
Trent Ltd                               24.42
UltraTech Cement Ltd                  1376.29

================================================================================

Average Trade Receivables (Current Year + Previous Year)/2:
                                     Avg_TR_2025  Avg_TR_2024  Avg_TR_2023  \
Adani Ports                             4049.650     3803.865     3205.235
Asian Paints Ltd                        4601.350     4762.995     4254.190
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                       7146.605     4716.250     3231.725
Bajaj Finance Ltd                       1330.640     1157.550     1043.660
Bharat Electronics Ltd                  8254.375     7212.930     6570.785
Bharti Airtel Ltd                       6091.700     4354.600     4018.850
Eternal Ltd                             1370.000      625.450      308.400
HCL Technologies Ltd                   25681.500    25513.500    23088.500
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  3408.000     3038.000     2657.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            30675.500    27808.500    24061.000
ITC Ltd                                 4372.745     3490.995     2709.035
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    51242.315    46751.240    45435.225
Mahindra and Mahindra Ltd               7869.550     7243.710     6700.985
Maruti Suzuki India Ltd                 5568.250     3949.100     2667.950
NTPC Ltd                               34034.990    31087.450    28083.650
Power Grid Corporation of India Ltd     9752.190    12250.490    11218.210
Reliance Industries Ltd                36874.500    30038.000    26044.000
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd      12147.740    11343.940    11015.700
Tata Motors Ltd                        15099.905    16344.890    14090.045
Tata Steel Ltd                          5761.795     7260.385    10251.835
Tata Consultancy Services Ltd          56311.500    51561.500    41810.000
Tech Mahindra Ltd                      11474.050    12141.350    12407.500
Titan Company Ltd                       1043.000      846.000      619.500
Trent Ltd                                 72.345       58.065       26.125
UltraTech Cement Ltd                    5084.205     4072.590     3469.315

                                     Avg_TR_2022  Avg_TR_2021  Avg_TR_2020  \
Adani Ports                             2697.695     3063.925     2995.900
Asian Paints Ltd                        3236.805     2198.695     1851.275
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                       2878.940     1647.260      455.915
Bajaj Finance Ltd                        868.605      793.640      836.280
Bharat Electronics Ltd                  6335.040     6643.005     6048.845
Bharti Airtel Ltd                       3846.950     4121.750     4453.200
Eternal Ltd                              144.885      126.495       96.730
HCL Technologies Ltd                   17167.000    13897.000    12918.500
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1997.000     1453.500     1482.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            20996.000    18890.500    16657.000
ITC Ltd                                 2481.800     2532.090     3298.880
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    44184.350    41480.650    38788.695
Mahindra and Mahindra Ltd               6190.855     6468.020     8109.395
Maruti Suzuki India Ltd                 1657.200     1628.800     2145.250
NTPC Ltd                               22530.075    19016.330    16339.055
Power Grid Corporation of India Ltd     6575.300     4358.120     4884.405
Reliance Industries Ltd                21327.000    19335.000    24872.500
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       9827.145     9241.320     9152.720
Tata Motors Ltd                        12560.600    11925.885    15084.430
Tata Steel Ltd                         10893.135     8712.375     9847.955
Tata Consultancy Services Ltd          32076.500    30305.500    28939.000
Tech Mahindra Ltd                       9203.100     7025.000     7267.900
Titan Company Ltd                        465.500      338.775      366.000
Trent Ltd                                 19.315       18.945       16.830
UltraTech Cement Ltd                    2821.670     2477.475     2585.125

                                     Avg_TR_2019  Avg_TR_2018  Avg_TR_2017  \
Adani Ports                             3163.785     2751.335     2200.425
Asian Paints Ltd                        1818.980     1588.615     1316.720
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                        361.700      310.050      222.410
Bajaj Finance Ltd                      17504.650    29929.350    12827.390
Bharat Electronics Ltd                  5193.985     4691.280     4045.085
Bharti Airtel Ltd                       5091.800     5311.600     5122.050
Eternal Ltd                               48.210       13.040        0.000
HCL Technologies Ltd                   10672.500     8970.000     8011.070
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1563.000     1197.500     1174.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            13984.500    12732.000    11826.000
ITC Ltd                                 3358.785     2578.290     2195.735
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    35749.975    31671.525    27356.975
Mahindra and Mahindra Ltd               8890.165     7844.540     6508.430
Maruti Suzuki India Ltd                 1889.100     1334.000     1263.000
NTPC Ltd                               10587.855     8888.040     8626.340
Power Grid Corporation of India Ltd     4184.060     3385.975     2935.700
Reliance Industries Ltd                23822.000    12866.000     6321.000
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       8349.740     7508.945     6989.135
Tata Motors Ltd                        19444.735    16984.425    13823.230
Tata Steel Ltd                         12113.260    12001.170    11826.520
Tata Consultancy Services Ltd          26144.500    23780.000    23345.000
Tech Mahindra Ltd                       6728.250     5917.800     5554.100
Titan Company Ltd                        358.070      251.645      200.050
Trent Ltd                                 15.820       10.510        9.455
UltraTech Cement Ltd                    2503.830     1988.860     1842.650

                                     Avg_TR_2016  Avg_TR_2015  Avg_TR_2014
Adani Ports                             1861.930     1357.665     1077.920
Asian Paints Ltd                        1183.345     1145.065     1045.580
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                         89.335        2.020        1.620
Bajaj Finance Ltd                          0.000        0.000        0.000
Bharat Electronics Ltd                  3763.615     3980.600     3759.720
Bharti Airtel Ltd                       5355.550     5725.650     6443.550
Eternal Ltd                                0.000        0.000        0.000
HCL Technologies Ltd                    7129.915     6110.765     5089.995
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1137.590     1021.135     1013.810
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            10521.500     9032.000     7717.000
ITC Ltd                                 1947.675     2205.860     1913.890
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    28057.175    28236.960    24699.730
Mahindra and Mahindra Ltd               5646.880     5600.790     5451.195
Maruti Suzuki India Ltd                 1233.850     1316.700     1489.150
NTPC Ltd                                8769.355     7987.790     6411.150
Power Grid Corporation of India Ltd     2473.215     1912.625     1554.835
Reliance Industries Ltd                 4890.000     7363.000     9580.500
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       6043.990     3756.370     2455.595
Tata Motors Ltd                        13075.055    11576.715    10758.445
Tata Steel Ltd                         12688.045    14657.820    14999.865
Tata Consultancy Services Ltd          22255.470    19334.170    16153.480
Tech Mahindra Ltd                       5488.200     4777.250     3026.100
Titan Company Ltd                        191.115      171.930      159.980
Trent Ltd                                 15.340       17.430       20.795
UltraTech Cement Ltd                    1793.515     1645.440     1504.175

================================================================================

Combined Data with Averages:
                                         2025      2024      2023      2022  \
Adani Ports                           4432.36   3666.94   3940.79   2469.68
Asian Paints Ltd                      4313.65   4889.05   4636.94   3871.44
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                     8319.35   5973.86   3458.64   3004.81
Bajaj Finance Ltd                     1416.39   1244.89   1070.21   1017.11
Bharat Electronics Ltd                9116.37   7392.38   7033.48   6108.09
Bharti Airtel Ltd                     7455.70   4727.70   3981.50   4056.20
Eternal Ltd                           1946.00    794.00    456.90    159.90
HCL Technologies Ltd                 25842.00  25521.00  25506.00  20671.00
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                3819.00   2997.00   3079.00   2236.00
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          31158.00  30193.00  25424.00  22698.00
ITC Ltd                               4719.67   4025.82   2956.17   2461.90
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  53713.68  48770.95  44731.53  46138.92
Mahindra and Mahindra Ltd             8279.70   7459.40   7028.02   6373.95
Maruti Suzuki India Ltd               6539.70   4596.80   3301.40   2034.50
NTPC Ltd                             34720.30  33349.68  28825.22  27342.08
Power Grid Corporation of India Ltd   7964.75  11539.63  12961.35   9475.07
Reliance Industries Ltd              42121.00  31628.00  28448.00  23640.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd    13046.11  11249.37  11438.51  10592.89

In [10]:

# Calculate averages for consecutive years
for i in range(len(tr.columns)-1):
    current_year = tr.columns[i]
    previous_year = tr.columns[i+1]
    avg_col_name = f'Avg_TR_{current_year}'
    average_tr[avg_col_name] = (tr[current_year] + tr[previous_year]) / 2
print("\n" + "="*80 + "\n")
print("Average Trade Receivables (Current Year + Previous Year)/2:")
print(average_tr)

================================================================================

Average Trade Receivables (Current Year + Previous Year)/2:
                                     Avg_TR_2025  Avg_TR_2024  Avg_TR_2023  \
Adani Ports                             4049.650     3803.865     3205.235
Asian Paints Ltd                        4601.350     4762.995     4254.190
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                       7146.605     4716.250     3231.725
Bajaj Finance Ltd                       1330.640     1157.550     1043.660
Bharat Electronics Ltd                  8254.375     7212.930     6570.785
Bharti Airtel Ltd                       6091.700     4354.600     4018.850
Eternal Ltd                             1370.000      625.450      308.400
HCL Technologies Ltd                   25681.500    25513.500    23088.500
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  3408.000     3038.000     2657.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            30675.500    27808.500    24061.000
ITC Ltd                                 4372.745     3490.995     2709.035
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    51242.315    46751.240    45435.225
Mahindra and Mahindra Ltd               7869.550     7243.710     6700.985
Maruti Suzuki India Ltd                 5568.250     3949.100     2667.950
NTPC Ltd                               34034.990    31087.450    28083.650
Power Grid Corporation of India Ltd     9752.190    12250.490    11218.210
Reliance Industries Ltd                36874.500    30038.000    26044.000
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd      12147.740    11343.940    11015.700
Tata Motors Ltd                        15099.905    16344.890    14090.045
Tata Steel Ltd                          5761.795     7260.385    10251.835
Tata Consultancy Services Ltd          56311.500    51561.500    41810.000
Tech Mahindra Ltd                      11474.050    12141.350    12407.500
Titan Company Ltd                       1043.000      846.000      619.500
Trent Ltd                                 72.345       58.065       26.125
UltraTech Cement Ltd                    5084.205     4072.590     3469.315

                                     Avg_TR_2022  Avg_TR_2021  Avg_TR_2020  \
Adani Ports                             2697.695     3063.925     2995.900
Asian Paints Ltd                        3236.805     2198.695     1851.275
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                       2878.940     1647.260      455.915
Bajaj Finance Ltd                        868.605      793.640      836.280
Bharat Electronics Ltd                  6335.040     6643.005     6048.845
Bharti Airtel Ltd                       3846.950     4121.750     4453.200
Eternal Ltd                              144.885      126.495       96.730
HCL Technologies Ltd                   17167.000    13897.000    12918.500
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1997.000     1453.500     1482.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            20996.000    18890.500    16657.000
ITC Ltd                                 2481.800     2532.090     3298.880
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    44184.350    41480.650    38788.695
Mahindra and Mahindra Ltd               6190.855     6468.020     8109.395
Maruti Suzuki India Ltd                 1657.200     1628.800     2145.250
NTPC Ltd                               22530.075    19016.330    16339.055
Power Grid Corporation of India Ltd     6575.300     4358.120     4884.405
Reliance Industries Ltd                21327.000    19335.000    24872.500
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       9827.145     9241.320     9152.720
Tata Motors Ltd                        12560.600    11925.885    15084.430
Tata Steel Ltd                         10893.135     8712.375     9847.955
Tata Consultancy Services Ltd          32076.500    30305.500    28939.000
Tech Mahindra Ltd                       9203.100     7025.000     7267.900
Titan Company Ltd                        465.500      338.775      366.000
Trent Ltd                                 19.315       18.945       16.830
UltraTech Cement Ltd                    2821.670     2477.475     2585.125

                                     Avg_TR_2019  Avg_TR_2018  Avg_TR_2017  \
Adani Ports                             3163.785     2751.335     2200.425
Asian Paints Ltd                        1818.980     1588.615     1316.720
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                        361.700      310.050      222.410
Bajaj Finance Ltd                      17504.650    29929.350    12827.390
Bharat Electronics Ltd                  5193.985     4691.280     4045.085
Bharti Airtel Ltd                       5091.800     5311.600     5122.050
Eternal Ltd                               48.210       13.040        0.000
HCL Technologies Ltd                   10672.500     8970.000     8011.070
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1563.000     1197.500     1174.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            13984.500    12732.000    11826.000
ITC Ltd                                 3358.785     2578.290     2195.735
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    35749.975    31671.525    27356.975
Mahindra and Mahindra Ltd               8890.165     7844.540     6508.430
Maruti Suzuki India Ltd                 1889.100     1334.000     1263.000
NTPC Ltd                               10587.855     8888.040     8626.340
Power Grid Corporation of India Ltd     4184.060     3385.975     2935.700
Reliance Industries Ltd                23822.000    12866.000     6321.000
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       8349.740     7508.945     6989.135
Tata Motors Ltd                        19444.735    16984.425    13823.230
Tata Steel Ltd                         12113.260    12001.170    11826.520
Tata Consultancy Services Ltd          26144.500    23780.000    23345.000
Tech Mahindra Ltd                       6728.250     5917.800     5554.100
Titan Company Ltd                        358.070      251.645      200.050
Trent Ltd                                 15.820       10.510        9.455
UltraTech Cement Ltd                    2503.830     1988.860     1842.650

                                     Avg_TR_2016  Avg_TR_2015  Avg_TR_2014
Adani Ports                             1861.930     1357.665     1077.920
Asian Paints Ltd                        1183.345     1145.065     1045.580
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                         89.335        2.020        1.620
Bajaj Finance Ltd                          0.000        0.000        0.000
Bharat Electronics Ltd                  3763.615     3980.600     3759.720
Bharti Airtel Ltd                       5355.550     5725.650     6443.550
Eternal Ltd                                0.000        0.000        0.000
HCL Technologies Ltd                    7129.915     6110.765     5089.995
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1137.590     1021.135     1013.810
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            10521.500     9032.000     7717.000
ITC Ltd                                 1947.675     2205.860     1913.890
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    28057.175    28236.960    24699.730
Mahindra and Mahindra Ltd               5646.880     5600.790     5451.195
Maruti Suzuki India Ltd                 1233.850     1316.700     1489.150
NTPC Ltd                                8769.355     7987.790     6411.150
Power Grid Corporation of India Ltd     2473.215     1912.625     1554.835
Reliance Industries Ltd                 4890.000     7363.000     9580.500
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       6043.990     3756.370     2455.595
Tata Motors Ltd                        13075.055    11576.715    10758.445
Tata Steel Ltd                         12688.045    14657.820    14999.865
Tata Consultancy Services Ltd          22255.470    19334.170    16153.480
Tech Mahindra Ltd                       5488.200     4777.250     3026.100
Titan Company Ltd                        191.115      171.930      159.980
Trent Ltd                                 15.340       17.430       20.795
UltraTech Cement Ltd                    1793.515     1645.440     1504.175

In [19]:
average_tr

,Avg_TR_2025,Avg_TR_2024,Avg_TR_2023,Avg_TR_2022,Avg_TR_2021,Avg_TR_2020,Avg_TR_2019,Avg_TR_2018,Avg_TR_2017,Avg_TR_2016,Avg_TR_2015,Avg_TR_2014
Adani Ports,4049.650,3803.865,3205.235,2697.695,3063.925,2995.900,3163.785,2751.335,2200.425,1861.930,1357.665,1077.920
Asian Paints Ltd,4601.350,4762.995,4254.190,3236.805,2198.695,1851.275,1818.980,1588.615,1316.720,1183.345,1145.065,1045.580
Axis Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Bajaj Finserv Ltd,7146.605,4716.250,3231.725,2878.940,1647.260,455.915,361.700,310.050,222.410,89.335,2.020,1.620
Bajaj Finance Ltd,1330.640,1157.550,1043.660,868.605,793.640,836.280,17504.650,29929.350,12827.390,0.000,0.000,0.000
Bharat Electronics Ltd,8254.375,7212.930,6570.785,6335.040,6643.005,6048.845,5193.985,4691.280,4045.085,3763.615,3980.600,3759.720
Bharti Airtel Ltd,6091.700,4354.600,4018.850,3846.950,4121.750,4453.200,5091.800,5311.600,5122.050,5355.550,5725.650,6443.550
Eternal Ltd,1370.000,625.450,308.400,144.885,126.495,96.730,48.210,13.040,0.000,0.000,0.000,0.000
HCL Technologies Ltd,25681.500,25513.500,23088.500,17167.000,13897.000,12918.500,10672.500,8970.000,8011.070,7129.915,6110.765,5089.995
HDFC Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Hindustan Unilever Ltd,3408.000,3038.000,2657.500,1997.000,1453.500,1482.500,1563.000,1197.500,1174.500,1137.590,1021.135,1013.810
ICICI Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Infosys Ltd,30675.500,27808.500,24061.000,20996.000,18890.500,16657.000,13984.500,12732.000,11826.000,10521.500,9032.000,7717.000
ITC Ltd,4372.745,3490.995,2709.035,2481.800,2532.090,3298.880,3358.785,2578.290,2195.735,1947.675,2205.860,1913.890
Kotak Mahindra Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Larsen & Toubro Ltd,51242.315,46751.240,45435.225,44184.350,41480.650,38788.695,35749.975,31671.525,27356.975,28057.175,28236.960,24699.730
Mahindra and Mahindra Ltd,7869.550,7243.710,6700.985,6190.855,6468.020,8109.395,8890.165,7844.540,6508.430,5646.880,5600.790,5451.195
Maruti Suzuki India Ltd,5568.250,3949.100,2667.950,1657.200,1628.800,2145.250,1889.100,1334.000,1263.000,1233.850,1316.700,1489.150
NTPC Ltd,34034.990,31087.450,28083.650,22530.075,19016.330,16339.055,10587.855,8888.040,8626.340,8769.355,7987.790,6411.150
Power Grid Corporation of India Ltd,9752.190,12250.490,11218.210,6575.300,4358.120,4884.405,4184.060,3385.975,2935.700,2473.215,1912.625,1554.835
Reliance Industries Ltd,36874.500,30038.000,26044.000,21327.000,19335.000,24872.500,23822.000,12866.000,6321.000,4890.000,7363.000,9580.500
State Bank of India,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Sun Pharmaceutical Industries Ltd,12147.740,11343.940,11015.700,9827.145,9241.320,9152.720,8349.740,7508.945,6989.135,6043.990,3756.370,2455.595
Tata Motors Ltd,15099.905,16344.890,14090.045,12560.600,11925.885,15084.430,19444.735,16984.425,13823.230,13075.055,11576.715,10758.445
Tata Steel Ltd,5761.795,7260.385,10251.835,10893.135,8712.375,9847.955,12113.260,12001.170,11826.520,12688.045,14657.820,14999.865
Tata Consultancy Services Ltd,56311.500,51561.500,41810.000,32076.500,30305.500,28939.000,26144.500,23780.000,23345.000,22255.470,19334.170,16153.480
Tech Mahindra Ltd,11474.050,12141.350,12407.500,9203.100,7025.000,7267.900,6728.250,5917.800,5554.100,5488.200,4777.250,3026.100
Titan Company Ltd,1043.000,846.000,619.500,465.500,338.775,366.000,358.070,251.645,200.050,191.115,171.930,159.980
Trent Ltd,72.345,58.065,26.125,19.315,18.945,16.830,15.820,10.510,9.455,15.340,17.430,20.795
UltraTech Cement Ltd,5084.205,4072.590,3469.315,2821.670,2477.475,2585.125,2503.830,1988.860,1842.650,1793.515,1645.440,1504.175

In [26]:
average_tr.to_csv('Average_Trade_Receivables.csv', index=True)

In [25]:
Revenue_From_Operations=Revenue_From_Operations.T
Revenue_From_Operations.rename(columns={0:'2025',1:'2024',2:'2023',3:'2022',4:'2021',5:'2020',6:'2019',7:'2018',8:'2017',9:'2016',10:'2015',11:'2014',12:'2013'},inplace=True)
Revenue_From_Operations

,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
Adani Ports,30475.33,26710.56,20617.64,15795.81,12425.50,11201.67,10780.98,11314.75,8427.35,7102.50,6151.98,4823.99,3576.63
Asian Paints Ltd,33797.36,35382.12,34367.83,28923.48,21485.20,20048.32,19062.38,16600.58,14872.52,14091.56,14005.33,12581.64,10906.01
Axis Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Bajaj Finserv Ltd,133821.05,110381.91,82071.24,68406.08,60591.20,54346.69,42604.00,32862.37,21149.64,8563.42,6471.24,4908.01,3821.09
Bajaj Finance Ltd,68264.59,53945.36,40288.71,30739.15,26504.52,26223.07,18397.29,12336.56,9258.03,6956.59,5119.97,0.00,0.00
Bharat Electronics Ltd,23117.30,19905.49,17404.18,15084.74,13849.71,12636.58,11854.70,10068.72,8336.58,7198.66,6895.32,6335.86,6151.14
Bharti Airtel Ltd,172985.20,149982.40,139144.80,116546.90,100615.80,87539.00,80780.20,83687.90,95468.30,96532.10,96100.70,85746.10,80311.20
Eternal Ltd,20243.00,12114.00,7079.40,4119.60,1915.75,2398.40,1296.30,466.36,0.00,0.00,0.00,0.00,0.00
HCL Technologies Ltd,117055.00,109913.00,101456.00,85651.00,75379.00,70676.00,60427.00,50569.00,47568.00,31135.94,36701.22,32143.66,25581.06
HDFC Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Hindustan Unilever Ltd,62288.00,60966.00,59549.00,51548.00,46321.00,39238.00,38684.00,34878.00,32464.00,31461.00,31199.72,28538.98,26317.15
ICICI Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Infosys Ltd,162990.00,153670.00,146767.00,121641.00,100472.00,90791.00,82675.00,70522.00,68484.00,62441.00,53319.00,50133.00,40352.00
ITC Ltd,74653.32,70315.49,70245.22,60081.36,48952.81,48979.08,47839.00,43122.90,42360.04,38804.19,38433.31,34984.70,31323.45
Kotak Mahindra Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Larsen & Toubro Ltd,254208.65,221112.91,181661.42,155672.46,134476.75,144308.05,133342.20,117908.12,107887.53,100034.24,89589.68,84429.34,74498.00
Mahindra and Mahindra Ltd,155645.26,135803.03,119040.38,89353.96,72678.98,74304.07,103015.23,90770.68,82069.37,74762.30,63862.55,66930.97,62643.54
Maruti Suzuki India Ltd,145109.90,134921.70,112511.30,83799.80,66571.80,71704.80,83038.50,78117.10,66924.70,56452.80,49295.00,43271.80,43215.90
NTPC Ltd,186144.66,176641.71,173985.61,132669.28,111267.88,109078.63,99615.00,86118.25,81193.50,72839.14,80034.89,78538.05,68891.48
Power Grid Corporation of India Ltd,44072.92,44202.75,44005.22,40784.69,39300.83,36800.13,34831.17,29904.96,25478.82,20576.04,17658.51,15597.89,13115.50
Reliance Industries Ltd,964693.00,901064.00,877835.00,699962.00,466924.00,597535.00,569209.00,391677.00,305382.00,273999.00,375435.00,434460.00,397062.00
State Bank of India,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Sun Pharmaceutical Industries Ltd,52041.25,47758.45,43278.87,38426.42,33139.18,32325.17,28686.28,25992.02,29993.93,27888.07,27286.50,16004.39,11238.89
Tata Motors Ltd,436821.00,434984.12,342874.58,275235.23,246972.17,258594.36,299190.59,288596.09,265498.47,269560.11,260734.33,230677.10,187652.84
Tata Steel Ltd,216840.35,227296.20,241636.25,242326.87,154719.28,146106.00,154691.63,130880.87,111562.05,105683.18,138318.91,147347.28,133416.60
Tata Consultancy Services Ltd,255324.00,240893.00,225458.00,191754.00,164177.00,156949.00,146463.00,123104.00,117966.00,108646.00,94648.41,81809.36,62989.48
Tech Mahindra Ltd,52988.30,51995.50,53290.20,44646.00,37855.10,36867.70,34742.10,30772.90,29140.80,26494.20,22621.30,18831.40,6873.10
Titan Company Ltd,57143.00,46751.00,37924.00,27417.00,20088.00,20767.70,19592.06,15946.49,13186.78,11187.74,11800.99,10826.15,10019.35
Trent Ltd,16873.72,12205.31,8112.33,4417.27,2546.90,3441.31,2585.75,2123.01,1779.99,1540.90,2236.77,2272.32,2017.28
UltraTech Cement Ltd,70857.27,67535.73,60462.60,49729.38,42677.00,41780.55,40903.81,30541.18,25091.62,24879.85,24064.75,21443.72,21156.12

In [27]:
Revenue_From_Operations.to_csv('Revenue_From_Operations.csv', index=True)

In [22]:
import pandas as pd

Trade_Receivables = pd.DataFrame({
    "Adani Ports": [4432.36, 3666.94, 3940.79, 2469.68, 2925.71, 3202.14, 2789.66, 3537.91, 1964.76, 2436.09, 1287.77, 1427.56, 728.28],
    "Asian Paints Ltd": [4313.65, 4889.05, 4636.94, 3871.44, 2602.17, 1795.22, 1907.33, 1730.63, 1446.60, 1186.84, 1179.85, 1110.28, 980.88],
    "Axis Bank Ltd": [0]*13,
    "Bajaj Finserv Ltd": [8319.35, 5973.86, 3458.64, 3004.81, 2753.07, 541.45, 370.38, 353.02, 267.08, 177.74, 0.93, 3.11, 0.13],
    "Bajaj Finance Ltd": [1416.39, 1244.89, 1070.21, 1017.11, 720.10, 867.18, 805.38, 34203.92, 25654.78, 0.00, 0.00, 0.00, 0.00],
    "Bharat Electronics Ltd": [9116.37, 7392.38, 7033.48, 6108.09, 6561.99, 6724.02, 5373.67, 5014.30, 4368.26, 3721.91, 3805.32, 4155.88, 3363.56],
    "Bharti Airtel Ltd": [7455.70, 4727.70, 3981.50, 4056.20, 3637.70, 4605.80, 4300.60, 5883.00, 4740.20, 5503.90, 5207.20, 6244.10, 6643.00],
    "Eternal Ltd": [1946.00, 794.00, 456.90, 159.90, 129.87, 123.12, 70.34, 26.08, 0.00, 0.00, 0.00, 0.00, 0.00],
    "HCL Technologies Ltd": [25842.00, 25521.00, 25506.00, 20671.00, 13663.00, 14131.00, 11706.00, 9639.00, 8301.00, 7721.14, 6538.69, 5682.84, 4497.15],
    "HDFC Bank Ltd": [0]*13,
    "Hindustan Unilever Ltd": [3819.00, 2997.00, 3079.00, 2236.00, 1758.00, 1149.00, 1816.00, 1310.00, 1085.00, 1264.00, 1011.18, 1031.09, 996.53],
    "ICICI Bank Ltd": [0]*13,
    "Infosys Ltd": [31158.00, 30193.00, 25424.00, 22698.00, 19294.00, 18487.00, 14827.00, 13142.00, 12322.00, 11330.00, 9713.00, 8351.00, 7083.00],
    "ITC Ltd": [4719.67, 4025.82, 2956.17, 2461.90, 2501.70, 2562.48, 4035.28, 2682.29, 2474.29, 1917.18, 1978.17, 2433.55, 1394.23],
    "Kotak Mahindra Bank Ltd": [0]*13,
    "Larsen & Toubro Ltd": [53713.68, 48770.95, 44731.53, 46138.92, 42229.78, 40731.52, 36845.87, 34654.08, 28688.97, 26024.98, 30089.37, 26384.55, 23014.91],
    "Mahindra and Mahindra Ltd": [8279.70, 7459.40, 7028.02, 6373.95, 6007.76, 6928.28, 9290.51, 8489.82, 7199.26, 5817.60, 5476.16, 5725.42, 5176.97],
    "Maruti Suzuki India Ltd": [6539.70, 4596.80, 3301.40, 2034.50, 1279.90, 1977.70, 2312.80, 1465.40, 1202.60, 1323.40, 1144.30, 1489.10, 1489.20],
    "NTPC Ltd": [34720.30, 33349.68, 28825.22, 27342.08, 17718.07, 20314.59, 12363.52, 8812.19, 8963.89, 8288.79, 9249.92, 6725.66, 6096.64],
    "Power Grid Corporation of India Ltd": [7964.75, 11539.63, 12961.35, 9475.07, 3675.53, 5040.71, 4728.10, 3640.02, 3131.93, 2739.47, 2206.96, 1618.29, 1491.38],
    "Reliance Industries Ltd": [42121.00, 31628.00, 28448.00, 23640.00, 19014.00, 19656.00, 30089.00, 17555.00, 8177.00, 4465.00, 5315.00, 9411.00, 9750.00],
    "State Bank of India": [0]*13,
    "Sun Pharmaceutical Industries Ltd": [13046.11, 11249.37, 11438.51, 10592.89, 9061.40, 9421.24, 8884.20, 7815.28, 7202.61, 6775.66, 5312.32, 2200.42, 2710.77],
    "Tata Motors Ltd": [13248.00, 16951.81, 15737.97, 12442.12, 12679.08, 11172.69, 18996.17, 19893.30, 14075.55, 13570.91, 12579.20, 10574.23, 10942.66],
    "Tata Steel Ltd": [5260.06, 6263.53, 8257.24, 12246.43, 9539.84, 7884.91, 11811.00, 12415.52, 11586.82, 12066.22, 13309.87, 16005.77, 13993.96],
    "Tata Consultancy Services Ltd": [59046.00, 53577.00, 49546.00, 34074.00, 30079.00, 30532.00, 27346.00, 24943.00, 22617.00, 24073.00, 20437.94, 18230.40, 14076.56],
    "Tech Mahindra Ltd": [11547.00, 11401.10, 12881.60, 11933.40, 6472.80, 7577.20, 6958.60, 6497.90, 5337.70, 5770.50, 5205.90, 4348.60, 1703.60],
    "Titan Company Ltd": [1068.00, 1018.00, 674.00, 565.00, 366.00, 311.55, 420.45, 295.69, 207.60, 192.50, 189.73, 154.13, 165.83],
    "Trent Ltd": [62.95, 81.74, 34.39, 17.86, 20.77, 17.12, 16.54, 15.10, 5.92, 12.99, 17.69, 17.17, 24.42],
    "UltraTech Cement Ltd": [5890.25, 4278.16, 3867.02, 3071.61, 2571.73, 2383.22, 2787.03, 2220.63, 1757.09, 1928.21, 1658.82, 1632.06, 1376.29]
})

# Transpose and rename columns for Trade Receivables
tr = Trade_Receivables.transpose()
tr.rename(columns={0:'2025',1:'2024',2:'2023',3:'2022',4:'2021',5:'2020',6:'2019',7:'2018',8:'2017',9:'2016',10:'2015',11:'2014',12:'2013'}, inplace=True)

# Calculate Average Trade Receivables
average_tr = pd.DataFrame()
for i in range(len(tr.columns)-1):
    current_year = tr.columns[i]
    previous_year = tr.columns[i+1]
    avg_col_name = f'Avg_TR_{current_year}'
    average_tr[avg_col_name] = (tr[current_year] + tr[previous_year]) / 2

# Calculate ATR (Accounts Receivable Turnover Ratio)
# ATR = Trade Receivables / Average Trade Receivables
atr_ratio = pd.DataFrame()

for i in range(len(average_tr.columns)):
    current_year = tr.columns[i]  # 2025, 2024, etc.
    avg_col = average_tr.columns[i]  # Avg_TR_2025, Avg_TR_2024, etc.
    
    # Calculate ATR for each year
    atr_ratio[f'ATR_{current_year}'] = tr[current_year] / average_tr[avg_col]

# Display results
print("Trade Receivables:")
print(tr)
print("\n" + "="*80 + "\n")
print("Average Trade Receivables:")
print(average_tr)
print("\n" + "="*80 + "\n")
print("Accounts Receivable Turnover Ratio (ATR = Trade Receivables / Average Trade Receivables):")
print(atr_ratio)

# Combine all data for better visualization
combined_data = pd.concat([tr, average_tr, atr_ratio], axis=1)
print("\n" + "="*80 + "\n")
print("Combined Data (Trade Receivables + Average TR + ATR Ratio):")
print(combined_data)

Trade Receivables:
                                         2025      2024      2023      2022  \
Adani Ports                           4432.36   3666.94   3940.79   2469.68
Asian Paints Ltd                      4313.65   4889.05   4636.94   3871.44
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                     8319.35   5973.86   3458.64   3004.81
Bajaj Finance Ltd                     1416.39   1244.89   1070.21   1017.11
Bharat Electronics Ltd                9116.37   7392.38   7033.48   6108.09
Bharti Airtel Ltd                     7455.70   4727.70   3981.50   4056.20
Eternal Ltd                           1946.00    794.00    456.90    159.90
HCL Technologies Ltd                 25842.00  25521.00  25506.00  20671.00
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                3819.00   2997.00   3079.00   2236.00
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          31158.00  30193.00  25424.00  22698.00
ITC Ltd                               4719.67   4025.82   2956.17   2461.90
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  53713.68  48770.95  44731.53  46138.92
Mahindra and Mahindra Ltd             8279.70   7459.40   7028.02   6373.95
Maruti Suzuki India Ltd               6539.70   4596.80   3301.40   2034.50
NTPC Ltd                             34720.30  33349.68  28825.22  27342.08
Power Grid Corporation of India Ltd   7964.75  11539.63  12961.35   9475.07
Reliance Industries Ltd              42121.00  31628.00  28448.00  23640.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd    13046.11  11249.37  11438.51  10592.89
Tata Motors Ltd                      13248.00  16951.81  15737.97  12442.12
Tata Steel Ltd                        5260.06   6263.53   8257.24  12246.43
Tata Consultancy Services Ltd        59046.00  53577.00  49546.00  34074.00
Tech Mahindra Ltd                    11547.00  11401.10  12881.60  11933.40
Titan Company Ltd                     1068.00   1018.00    674.00    565.00
Trent Ltd                               62.95     81.74     34.39     17.86
UltraTech Cement Ltd                  5890.25   4278.16   3867.02   3071.61

                                         2021      2020      2019      2018  \
Adani Ports                           2925.71   3202.14   2789.66   3537.91
Asian Paints Ltd                      2602.17   1795.22   1907.33   1730.63
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                     2753.07    541.45    370.38    353.02
Bajaj Finance Ltd                      720.10    867.18    805.38  34203.92
Bharat Electronics Ltd                6561.99   6724.02   5373.67   5014.30
Bharti Airtel Ltd                     3637.70   4605.80   4300.60   5883.00
Eternal Ltd                            129.87    123.12     70.34     26.08
HCL Technologies Ltd                 13663.00  14131.00  11706.00   9639.00
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                1758.00   1149.00   1816.00   1310.00
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          19294.00  18487.00  14827.00  13142.00
ITC Ltd                               2501.70   2562.48   4035.28   2682.29
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  42229.78  40731.52  36845.87  34654.08
Mahindra and Mahindra Ltd             6007.76   6928.28   9290.51   8489.82
Maruti Suzuki India Ltd               1279.90   1977.70   2312.80   1465.40
NTPC Ltd                             17718.07  20314.59  12363.52   8812.19
Power Grid Corporation of India Ltd   3675.53   5040.71   4728.10   3640.02
Reliance Industries Ltd              19014.00  19656.00  30089.00  17555.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd     9061.40   9421.24   8884.20   7815.28
Tata Motors Ltd                      12679.08  11172.69  18996.17  19893.30
Tata Steel Ltd                        9539.84   7884.91  11811.00  12415.52
Tata Consultancy Services Ltd        30079.00  30532.00  27346.00  24943.00
Tech Mahindra Ltd                     6472.80   7577.20   6958.60   6497.90
Titan Company Ltd                      366.00    311.55    420.45    295.69
Trent Ltd                               20.77     17.12     16.54     15.10
UltraTech Cement Ltd                  2571.73   2383.22   2787.03   2220.63

                                         2017      2016      2015      2014  \
Adani Ports                           1964.76   2436.09   1287.77   1427.56
Asian Paints Ltd                      1446.60   1186.84   1179.85   1110.28
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                      267.08    177.74      0.93      3.11
Bajaj Finance Ltd                    25654.78      0.00      0.00      0.00
Bharat Electronics Ltd                4368.26   3721.91   3805.32   4155.88
Bharti Airtel Ltd                     4740.20   5503.90   5207.20   6244.10
Eternal Ltd                              0.00      0.00      0.00      0.00
HCL Technologies Ltd                  8301.00   7721.14   6538.69   5682.84
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                1085.00   1264.00   1011.18   1031.09
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          12322.00  11330.00   9713.00   8351.00
ITC Ltd                               2474.29   1917.18   1978.17   2433.55
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  28688.97  26024.98  30089.37  26384.55
Mahindra and Mahindra Ltd             7199.26   5817.60   5476.16   5725.42
Maruti Suzuki India Ltd               1202.60   1323.40   1144.30   1489.10
NTPC Ltd                              8963.89   8288.79   9249.92   6725.66
Power Grid Corporation of India Ltd   3131.93   2739.47   2206.96   1618.29
Reliance Industries Ltd               8177.00   4465.00   5315.00   9411.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd     7202.61   6775.66   5312.32   2200.42
Tata Motors Ltd                      14075.55  13570.91  12579.20  10574.23
Tata Steel Ltd                       11586.82  12066.22  13309.87  16005.77
Tata Consultancy Services Ltd        22617.00  24073.00  20437.94  18230.40
Tech Mahindra Ltd                     5337.70   5770.50   5205.90   4348.60
Titan Company Ltd                      207.60    192.50    189.73    154.13
Trent Ltd                                5.92     12.99     17.69     17.17
UltraTech Cement Ltd                  1757.09   1928.21   1658.82   1632.06

                                         2013
Adani Ports                            728.28
Asian Paints Ltd                       980.88
Axis Bank Ltd                            0.00
Bajaj Finserv Ltd                        0.13
Bajaj Finance Ltd                        0.00
Bharat Electronics Ltd                3363.56
Bharti Airtel Ltd                     6643.00
Eternal Ltd                              0.00
HCL Technologies Ltd                  4497.15
HDFC Bank Ltd                            0.00
Hindustan Unilever Ltd                 996.53
ICICI Bank Ltd                           0.00
Infosys Ltd                           7083.00
ITC Ltd                               1394.23
Kotak Mahindra Bank Ltd                  0.00
Larsen & Toubro Ltd                  23014.91
Mahindra and Mahindra Ltd             5176.97
Maruti Suzuki India Ltd               1489.20
NTPC Ltd                              6096.64
Power Grid Corporation of India Ltd   1491.38
Reliance Industries Ltd               9750.00
State Bank of India                      0.00
Sun Pharmaceutical Industries Ltd     2710.77
Tata Motors Ltd                      10942.66
Tata Steel Ltd                       13993.96
Tata Consultancy Services Ltd        14076.56
Tech Mahindra Ltd                     1703.60
Titan Company Ltd                      165.83
Trent Ltd                               24.42
UltraTech Cement Ltd                  1376.29

================================================================================

Average Trade Receivables:
                                     Avg_TR_2025  Avg_TR_2024  Avg_TR_2023  \
Adani Ports                             4049.650     3803.865     3205.235
Asian Paints Ltd                        4601.350     4762.995     4254.190
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                       7146.605     4716.250     3231.725
Bajaj Finance Ltd                       1330.640     1157.550     1043.660
Bharat Electronics Ltd                  8254.375     7212.930     6570.785
Bharti Airtel Ltd                       6091.700     4354.600     4018.850
Eternal Ltd                             1370.000      625.450      308.400
HCL Technologies Ltd                   25681.500    25513.500    23088.500
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  3408.000     3038.000     2657.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            30675.500    27808.500    24061.000
ITC Ltd                                 4372.745     3490.995     2709.035
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    51242.315    46751.240    45435.225
Mahindra and Mahindra Ltd               7869.550     7243.710     6700.985
Maruti Suzuki India Ltd                 5568.250     3949.100     2667.950
NTPC Ltd                               34034.990    31087.450    28083.650
Power Grid Corporation of India Ltd     9752.190    12250.490    11218.210
Reliance Industries Ltd                36874.500    30038.000    26044.000
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd      12147.740    11343.940    11015.700
Tata Motors Ltd                        15099.905    16344.890    14090.045
Tata Steel Ltd                          5761.795     7260.385    10251.835
Tata Consultancy Services Ltd          56311.500    51561.500    41810.000
Tech Mahindra Ltd                      11474.050    12141.350    12407.500
Titan Company Ltd                       1043.000      846.000      619.500
Trent Ltd                                 72.345       58.065       26.125
UltraTech Cement Ltd                    5084.205     4072.590     3469.315

                                     Avg_TR_2022  Avg_TR_2021  Avg_TR_2020  \
Adani Ports                             2697.695     3063.925     2995.900
Asian Paints Ltd                        3236.805     2198.695     1851.275
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                       2878.940     1647.260      455.915
Bajaj Finance Ltd                        868.605      793.640      836.280
Bharat Electronics Ltd                  6335.040     6643.005     6048.845
Bharti Airtel Ltd                       3846.950     4121.750     4453.200
Eternal Ltd                              144.885      126.495       96.730
HCL Technologies Ltd                   17167.000    13897.000    12918.500
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1997.000     1453.500     1482.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            20996.000    18890.500    16657.000
ITC Ltd                                 2481.800     2532.090     3298.880
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    44184.350    41480.650    38788.695
Mahindra and Mahindra Ltd               6190.855     6468.020     8109.395
Maruti Suzuki India Ltd                 1657.200     1628.800     2145.250
NTPC Ltd                               22530.075    19016.330    16339.055
Power Grid Corporation of India Ltd     6575.300     4358.120     4884.405
Reliance Industries Ltd                21327.000    19335.000    24872.500
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       9827.145     9241.320     9152.720
Tata Motors Ltd                        12560.600    11925.885    15084.430
Tata Steel Ltd                         10893.135     8712.375     9847.955
Tata Consultancy Services Ltd          32076.500    30305.500    28939.000
Tech Mahindra Ltd                       9203.100     7025.000     7267.900
Titan Company Ltd                        465.500      338.775      366.000
Trent Ltd                                 19.315       18.945       16.830
UltraTech Cement Ltd                    2821.670     2477.475     2585.125

                                     Avg_TR_2019  Avg_TR_2018  Avg_TR_2017  \
Adani Ports                             3163.785     2751.335     2200.425
Asian Paints Ltd                        1818.980     1588.615     1316.720
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                        361.700      310.050      222.410
Bajaj Finance Ltd                      17504.650    29929.350    12827.390
Bharat Electronics Ltd                  5193.985     4691.280     4045.085
Bharti Airtel Ltd                       5091.800     5311.600     5122.050
Eternal Ltd                               48.210       13.040        0.000
HCL Technologies Ltd                   10672.500     8970.000     8011.070
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1563.000     1197.500     1174.500
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            13984.500    12732.000    11826.000
ITC Ltd                                 3358.785     2578.290     2195.735
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    35749.975    31671.525    27356.975
Mahindra and Mahindra Ltd               8890.165     7844.540     6508.430
Maruti Suzuki India Ltd                 1889.100     1334.000     1263.000
NTPC Ltd                               10587.855     8888.040     8626.340
Power Grid Corporation of India Ltd     4184.060     3385.975     2935.700
Reliance Industries Ltd                23822.000    12866.000     6321.000
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       8349.740     7508.945     6989.135
Tata Motors Ltd                        19444.735    16984.425    13823.230
Tata Steel Ltd                         12113.260    12001.170    11826.520
Tata Consultancy Services Ltd          26144.500    23780.000    23345.000
Tech Mahindra Ltd                       6728.250     5917.800     5554.100
Titan Company Ltd                        358.070      251.645      200.050
Trent Ltd                                 15.820       10.510        9.455
UltraTech Cement Ltd                    2503.830     1988.860     1842.650

                                     Avg_TR_2016  Avg_TR_2015  Avg_TR_2014
Adani Ports                             1861.930     1357.665     1077.920
Asian Paints Ltd                        1183.345     1145.065     1045.580
Axis Bank Ltd                              0.000        0.000        0.000
Bajaj Finserv Ltd                         89.335        2.020        1.620
Bajaj Finance Ltd                          0.000        0.000        0.000
Bharat Electronics Ltd                  3763.615     3980.600     3759.720
Bharti Airtel Ltd                       5355.550     5725.650     6443.550
Eternal Ltd                                0.000        0.000        0.000
HCL Technologies Ltd                    7129.915     6110.765     5089.995
HDFC Bank Ltd                              0.000        0.000        0.000
Hindustan Unilever Ltd                  1137.590     1021.135     1013.810
ICICI Bank Ltd                             0.000        0.000        0.000
Infosys Ltd                            10521.500     9032.000     7717.000
ITC Ltd                                 1947.675     2205.860     1913.890
Kotak Mahindra Bank Ltd                    0.000        0.000        0.000
Larsen & Toubro Ltd                    28057.175    28236.960    24699.730
Mahindra and Mahindra Ltd               5646.880     5600.790     5451.195
Maruti Suzuki India Ltd                 1233.850     1316.700     1489.150
NTPC Ltd                                8769.355     7987.790     6411.150
Power Grid Corporation of India Ltd     2473.215     1912.625     1554.835
Reliance Industries Ltd                 4890.000     7363.000     9580.500
State Bank of India                        0.000        0.000        0.000
Sun Pharmaceutical Industries Ltd       6043.990     3756.370     2455.595
Tata Motors Ltd                        13075.055    11576.715    10758.445
Tata Steel Ltd                         12688.045    14657.820    14999.865
Tata Consultancy Services Ltd          22255.470    19334.170    16153.480
Tech Mahindra Ltd                       5488.200     4777.250     3026.100
Titan Company Ltd                        191.115      171.930      159.980
Trent Ltd                                 15.340       17.430       20.795
UltraTech Cement Ltd                    1793.515     1645.440     1504.175

================================================================================

Accounts Receivable Turnover Ratio (ATR = Trade Receivables / Average Trade Receivables):
                                     ATR_2025  ATR_2024  ATR_2023  ATR_2022  \
Adani Ports                          1.094504  0.964004  1.229486  0.915478
Asian Paints Ltd                     0.937475  1.026465  1.089970  1.196068
Axis Bank Ltd                             NaN       NaN       NaN       NaN
Bajaj Finserv Ltd                    1.164098  1.266655  1.070215  1.043721
Bajaj Finance Ltd                    1.064443  1.075452  1.025439  1.170970
Bharat Electronics Ltd               1.104429  1.024879  1.070417  0.964175
Bharti Airtel Ltd                    1.223911  1.085680  0.990706  1.054394
Eternal Ltd                          1.420438  1.269486  1.481518  1.103634
HCL Technologies Ltd                 1.006250  1.000294  1.104706  1.204113
HDFC Bank Ltd                             NaN       NaN       NaN       NaN
Hindustan Unilever Ltd               1.120599  0.986504  1.158608  1.119680
ICICI Bank Ltd                            NaN       NaN       NaN       NaN
Infosys Ltd                          1.015729  1.085747  1.056648  1.081063
ITC Ltd                              1.079338  1.153201  1.091226  0.991982
Kotak Mahindra Bank Ltd                   NaN       NaN       NaN       NaN
Larsen & Toubro Ltd                  1.048229  1.043201  0.984512  1.044237
Mahindra and Mahindra Ltd            1.052119  1.029776  1.048804  1.029575
Maruti Suzuki India Ltd              1.174462  1.164012  1.237429  1.227673
NTPC Ltd                             1.020135  1.072770  1.026406  1.213581
Power Grid Corporation of India Ltd  0.816714  0.941973  1.155385  1.441010
Reliance Industries Ltd              1.142280  1.052933  1.092305  1.108454
State Bank of India                       NaN       NaN       NaN       NaN
Sun Pharmaceutical Industries Ltd    1.073954  0.991663  1.038382  1.077921

In [23]:
atr_ratio

,ATR_2025,ATR_2024,ATR_2023,ATR_2022,ATR_2021,ATR_2020,ATR_2019,ATR_2018,ATR_2017,ATR_2016,ATR_2015,ATR_2014
Adani Ports,1.094504,0.964004,1.229486,0.915478,0.954890,1.068841,0.881748,1.285888,0.892900,1.308368,0.948518,1.324365
Asian Paints Ltd,0.937475,1.026465,1.089970,1.196068,1.183507,0.969721,1.048571,1.089395,1.098639,1.002953,1.030378,1.061880
Axis Bank Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bajaj Finserv Ltd,1.164098,1.266655,1.070215,1.043721,1.671303,1.187612,1.023998,1.138591,1.200845,1.989590,0.460396,1.919753
Bajaj Finance Ltd,1.064443,1.075452,1.025439,1.170970,0.907338,1.036949,0.046009,1.142822,2.000000,NaN,NaN,NaN
Bharat Electronics Ltd,1.104429,1.024879,1.070417,0.964175,0.987804,1.111620,1.034595,1.068855,1.079893,0.988919,0.955966,1.105370
Bharti Airtel Ltd,1.223911,1.085680,0.990706,1.054394,0.882562,1.034267,0.844613,1.107576,0.925450,1.027700,0.909451,0.969047
Eternal Ltd,1.420438,1.269486,1.481518,1.103634,1.026681,1.272821,1.459033,2.000000,NaN,NaN,NaN,NaN
HCL Technologies Ltd,1.006250,1.000294,1.104706,1.204113,0.983162,1.093858,1.096838,1.074582,1.036191,1.082922,1.070028,1.116473
HDFC Bank Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hindustan Unilever Ltd,1.120599,0.986504,1.158608,1.119680,1.209494,0.775042,1.161868,1.093946,0.923797,1.111121,0.990251,1.017045
ICICI Bank Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Infosys Ltd,1.015729,1.085747,1.056648,1.081063,1.021360,1.109864,1.060245,1.032202,1.041941,1.076843,1.075399,1.082156
ITC Ltd,1.079338,1.153201,1.091226,0.991982,0.987998,0.776773,1.201411,1.040337,1.126862,0.984343,0.896779,1.271520
Kotak Mahindra Bank Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Larsen & Toubro Ltd,1.048229,1.043201,0.984512,1.044237,1.018060,1.050087,1.030654,1.094171,1.048689,0.927570,1.065602,1.068212
Mahindra and Mahindra Ltd,1.052119,1.029776,1.048804,1.029575,0.928841,0.854352,1.045032,1.082258,1.106144,1.030233,0.977748,1.050305
Maruti Suzuki India Ltd,1.174462,1.164012,1.237429,1.227673,0.785793,0.921897,1.224287,1.098501,0.952177,1.072578,0.869067,0.999966
NTPC Ltd,1.020135,1.072770,1.026406,1.213581,0.931729,1.243315,1.167708,0.991466,1.039130,0.945200,1.158007,1.049057
Power Grid Corporation of India Ltd,0.816714,0.941973,1.155385,1.441010,0.843375,1.032001,1.130027,1.075029,1.066843,1.107655,1.153891,1.040811
Reliance Industries Ltd,1.142280,1.052933,1.092305,1.108454,0.983398,0.790270,1.263076,1.364449,1.293624,0.913088,0.721853,0.982308
State Bank of India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sun Pharmaceutical Industries Ltd,1.073954,0.991663,1.038382,1.077921,0.980531,1.029338,1.064009,1.040796,1.030544,1.121057,1.414216,0.896084
Tata Motors Ltd,0.877357,1.037132,1.116957,0.990567,1.063156,0.740677,0.976931,1.171267,1.018253,1.037924,1.086595,0.982877
Tata Steel Ltd,0.912920,0.862699,0.805440,1.124234,1.094976,0.800665,0.975047,1.034526,0.979732,0.950991,0.908039,1.067061
Tata Consultancy Services Ltd,1.048560,1.039089,1.185028,1.062273,0.992526,1.055047,1.045956,1.048907,0.968816,1.081667,1.057089,1.128574
Tech Mahindra Ltd,1.006358,0.939031,1.038211,1.296672,0.921395,1.042557,1.034236,1.098026,0.961038,1.051438,1.089727,1.437031
Titan Company Ltd,1.023969,1.203310,1.087974,1.213749,1.080363,0.851230,1.174212,1.175028,1.037741,1.007247,1.103531,0.963433
Trent Ltd,0.870136,1.407733,1.316364,0.924670,1.096331,1.017231,1.045512,1.436727,0.626124,0.846806,1.014917,0.825679
UltraTech Cement Ltd,1.158539,1.050476,1.114635,1.088579,1.038045,0.921897,1.113107,1.116534,0.953567,1.075101,1.008132,1.085020

In [24]:
atr_ratio.shape

(30, 12)

In [28]:
a=pd.read_csv('Average_Trade_Receivables.csv')
a

,Unnamed: 0,Avg_TR_2025,Avg_TR_2024,Avg_TR_2023,Avg_TR_2022,Avg_TR_2021,Avg_TR_2020,Avg_TR_2019,Avg_TR_2018,Avg_TR_2017,Avg_TR_2016,Avg_TR_2015,Avg_TR_2014
0,Adani Ports,4049.650,3803.865,3205.235,2697.695,3063.925,2995.900,3163.785,2751.335,2200.425,1861.930,1357.665,1077.920
1,Asian Paints Ltd,4601.350,4762.995,4254.190,3236.805,2198.695,1851.275,1818.980,1588.615,1316.720,1183.345,1145.065,1045.580
2,Axis Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,Bajaj Finserv Ltd,7146.605,4716.250,3231.725,2878.940,1647.260,455.915,361.700,310.050,222.410,89.335,2.020,1.620
4,Bajaj Finance Ltd,1330.640,1157.550,1043.660,868.605,793.640,836.280,17504.650,29929.350,12827.390,0.000,0.000,0.000
5,Bharat Electronics Ltd,8254.375,7212.930,6570.785,6335.040,6643.005,6048.845,5193.985,4691.280,4045.085,3763.615,3980.600,3759.720
6,Bharti Airtel Ltd,6091.700,4354.600,4018.850,3846.950,4121.750,4453.200,5091.800,5311.600,5122.050,5355.550,5725.650,6443.550
7,Eternal Ltd,1370.000,625.450,308.400,144.885,126.495,96.730,48.210,13.040,0.000,0.000,0.000,0.000
8,HCL Technologies Ltd,25681.500,25513.500,23088.500,17167.000,13897.000,12918.500,10672.500,8970.000,8011.070,7129.915,6110.765,5089.995
9,HDFC Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
10,Hindustan Unilever Ltd,3408.000,3038.000,2657.500,1997.000,1453.500,1482.500,1563.000,1197.500,1174.500,1137.590,1021.135,1013.810
11,ICICI Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
12,Infosys Ltd,30675.500,27808.500,24061.000,20996.000,18890.500,16657.000,13984.500,12732.000,11826.000,10521.500,9032.000,7717.000
13,ITC Ltd,4372.745,3490.995,2709.035,2481.800,2532.090,3298.880,3358.785,2578.290,2195.735,1947.675,2205.860,1913.890
14,Kotak Mahindra Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
15,Larsen & Toubro Ltd,51242.315,46751.240,45435.225,44184.350,41480.650,38788.695,35749.975,31671.525,27356.975,28057.175,28236.960,24699.730
16,Mahindra and Mahindra Ltd,7869.550,7243.710,6700.985,6190.855,6468.020,8109.395,8890.165,7844.540,6508.430,5646.880,5600.790,5451.195
17,Maruti Suzuki India Ltd,5568.250,3949.100,2667.950,1657.200,1628.800,2145.250,1889.100,1334.000,1263.000,1233.850,1316.700,1489.150
18,NTPC Ltd,34034.990,31087.450,28083.650,22530.075,19016.330,16339.055,10587.855,8888.040,8626.340,8769.355,7987.790,6411.150
19,Power Grid Corporation of India Ltd,9752.190,12250.490,11218.210,6575.300,4358.120,4884.405,4184.060,3385.975,2935.700,2473.215,1912.625,1554.835
20,Reliance Industries Ltd,36874.500,30038.000,26044.000,21327.000,19335.000,24872.500,23822.000,12866.000,6321.000,4890.000,7363.000,9580.500
21,State Bank of India,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22,Sun Pharmaceutical Industries Ltd,12147.740,11343.940,11015.700,9827.145,9241.320,9152.720,8349.740,7508.945,6989.135,6043.990,3756.370,2455.595
23,Tata Motors Ltd,15099.905,16344.890,14090.045,12560.600,11925.885,15084.430,19444.735,16984.425,13823.230,13075.055,11576.715,10758.445
24,Tata Steel Ltd,5761.795,7260.385,10251.835,10893.135,8712.375,9847.955,12113.260,12001.170,11826.520,12688.045,14657.820,14999.865
25,Tata Consultancy Services Ltd,56311.500,51561.500,41810.000,32076.500,30305.500,28939.000,26144.500,23780.000,23345.000,22255.470,19334.170,16153.480
26,Tech Mahindra Ltd,11474.050,12141.350,12407.500,9203.100,7025.000,7267.900,6728.250,5917.800,5554.100,5488.200,4777.250,3026.100
27,Titan Company Ltd,1043.000,846.000,619.500,465.500,338.775,366.000,358.070,251.645,200.050,191.115,171.930,159.980
28,Trent Ltd,72.345,58.065,26.125,19.315,18.945,16.830,15.820,10.510,9.455,15.340,17.430,20.795
29,UltraTech Cement Ltd,5084.205,4072.590,3469.315,2821.670,2477.475,2585.125,2503.830,1988.860,1842.650,1793.515,1645.440,1504.175

In [3]:
import pandas as pd

# Your existing DataFrame creation code
Trade_Receivables = pd.DataFrame({
    "Adani Ports": [4432.36, 3666.94, 3940.79, 2469.68, 2925.71, 3202.14, 2789.66, 3537.91, 1964.76, 2436.09, 1287.77, 1427.56, 728.28],
    "Asian Paints Ltd": [4313.65, 4889.05, 4636.94, 3871.44, 2602.17, 1795.22, 1907.33, 1730.63, 1446.60, 1186.84, 1179.85, 1110.28, 980.88],
    "Axis Bank Ltd": [0]*13,
    "Bajaj Finserv Ltd": [8319.35, 5973.86, 3458.64, 3004.81, 2753.07, 541.45, 370.38, 353.02, 267.08, 177.74, 0.93, 3.11, 0.13],
    "Bajaj Finance Ltd": [1416.39, 1244.89, 1070.21, 1017.11, 720.10, 867.18, 805.38, 34203.92, 25654.78, 0.00, 0.00, 0.00, 0.00],
    "Bharat Electronics Ltd": [9116.37, 7392.38, 7033.48, 6108.09, 6561.99, 6724.02, 5373.67, 5014.30, 4368.26, 3721.91, 3805.32, 4155.88, 3363.56],
    "Bharti Airtel Ltd": [7455.70, 4727.70, 3981.50, 4056.20, 3637.70, 4605.80, 4300.60, 5883.00, 4740.20, 5503.90, 5207.20, 6244.10, 6643.00],
    "Eternal Ltd": [1946.00, 794.00, 456.90, 159.90, 129.87, 123.12, 70.34, 26.08, 0.00, 0.00, 0.00, 0.00, 0.00],
    "HCL Technologies Ltd": [25842.00, 25521.00, 25506.00, 20671.00, 13663.00, 14131.00, 11706.00, 9639.00, 8301.00, 7721.14, 6538.69, 5682.84, 4497.15],
    "HDFC Bank Ltd": [0]*13,
    "Hindustan Unilever Ltd": [3819.00, 2997.00, 3079.00, 2236.00, 1758.00, 1149.00, 1816.00, 1310.00, 1085.00, 1264.00, 1011.18, 1031.09, 996.53],
    "ICICI Bank Ltd": [0]*13,
    "Infosys Ltd": [31158.00, 30193.00, 25424.00, 22698.00, 19294.00, 18487.00, 14827.00, 13142.00, 12322.00, 11330.00, 9713.00, 8351.00, 7083.00],
    "ITC Ltd": [4719.67, 4025.82, 2956.17, 2461.90, 2501.70, 2562.48, 4035.28, 2682.29, 2474.29, 1917.18, 1978.17, 2433.55, 1394.23],
    "Kotak Mahindra Bank Ltd": [0]*13,
    "Larsen & Toubro Ltd": [53713.68, 48770.95, 44731.53, 46138.92, 42229.78, 40731.52, 36845.87, 34654.08, 28688.97, 26024.98, 30089.37, 26384.55, 23014.91],
    "Mahindra and Mahindra Ltd": [8279.70, 7459.40, 7028.02, 6373.95, 6007.76, 6928.28, 9290.51, 8489.82, 7199.26, 5817.60, 5476.16, 5725.42, 5176.97],
    "Maruti Suzuki India Ltd": [6539.70, 4596.80, 3301.40, 2034.50, 1279.90, 1977.70, 2312.80, 1465.40, 1202.60, 1323.40, 1144.30, 1489.10, 1489.20],
    "NTPC Ltd": [34720.30, 33349.68, 28825.22, 27342.08, 17718.07, 20314.59, 12363.52, 8812.19, 8963.89, 8288.79, 9249.92, 6725.66, 6096.64],
    "Power Grid Corporation of India Ltd": [7964.75, 11539.63, 12961.35, 9475.07, 3675.53, 5040.71, 4728.10, 3640.02, 3131.93, 2739.47, 2206.96, 1618.29, 1491.38],
    "Reliance Industries Ltd": [42121.00, 31628.00, 28448.00, 23640.00, 19014.00, 19656.00, 30089.00, 17555.00, 8177.00, 4465.00, 5315.00, 9411.00, 9750.00],
    "State Bank of India": [0]*13,
    "Sun Pharmaceutical Industries Ltd": [13046.11, 11249.37, 11438.51, 10592.89, 9061.40, 9421.24, 8884.20, 7815.28, 7202.61, 6775.66, 5312.32, 2200.42, 2710.77],
    "Tata Motors Ltd": [13248.00, 16951.81, 15737.97, 12442.12, 12679.08, 11172.69, 18996.17, 19893.30, 14075.55, 13570.91, 12579.20, 10574.23, 10942.66],
    "Tata Steel Ltd": [5260.06, 6263.53, 8257.24, 12246.43, 9539.84, 7884.91, 11811.00, 12415.52, 11586.82, 12066.22, 13309.87, 16005.77, 13993.96],
    "Tata Consultancy Services Ltd": [59046.00, 53577.00, 49546.00, 34074.00, 30079.00, 30532.00, 27346.00, 24943.00, 22617.00, 24073.00, 20437.94, 18230.40, 14076.56],
    "Tech Mahindra Ltd": [11547.00, 11401.10, 12881.60, 11933.40, 6472.80, 7577.20, 6958.60, 6497.90, 5337.70, 5770.50, 5205.90, 4348.60, 1703.60],
    "Titan Company Ltd": [1068.00, 1018.00, 674.00, 565.00, 366.00, 311.55, 420.45, 295.69, 207.60, 192.50, 189.73, 154.13, 165.83],
    "Trent Ltd": [62.95, 81.74, 34.39, 17.86, 20.77, 17.12, 16.54, 15.10, 5.92, 12.99, 17.69, 17.17, 24.42],
    "UltraTech Cement Ltd": [5890.25, 4278.16, 3867.02, 3071.61, 2571.73, 2383.22, 2787.03, 2220.63, 1757.09, 1928.21, 1658.82, 1632.06, 1376.29]
})

# Transpose and rename columns
tr = Trade_Receivables.transpose()
tr.rename(columns={0:'2025',1:'2024',2:'2023',3:'2022',4:'2021',5:'2020',6:'2019',7:'2018',8:'2017',9:'2016',10:'2015',11:'2014',12:'2013'}, inplace=True)

# Calculate Average Trade Receivables
# Since 2025 is first, we'll calculate from 2024 backwards to 2013
# Formula: Average Trade Receivables = (Trade Receivables current year + Trade Receivables previous year)/2

# Create a new DataFrame for average trade receivables
avg_tr = pd.DataFrame(index=tr.index)

# Years in chronological order (from most recent to oldest)
years = ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013']

# Calculate average trade receivables
for i in range(len(years)-1):
    current_year = years[i]
    previous_year = years[i+1]
    avg_tr[f'Avg_{current_year}'] = (tr[current_year] + tr[previous_year]) / 2

# For 2013: (2013 + 0)/2 as requested
avg_tr['Avg_2013'] = (tr['2013'] + 0) / 2

# Reorder columns to match chronological order
avg_tr = avg_tr[['Avg_2025', 'Avg_2024', 'Avg_2023', 'Avg_2022', 'Avg_2021', 'Avg_2020', 
                 'Avg_2019', 'Avg_2018', 'Avg_2017', 'Avg_2016', 'Avg_2015', 'Avg_2014', 'Avg_2013']]

# Display the results
print("Original Trade Receivables:")
print(tr)
print("\nAverage Trade Receivables:")
print(avg_tr)

# If you want to combine both DataFrames
combined = pd.concat([tr, avg_tr], axis=1)
print("\nCombined DataFrame (Original + Average):")
print(combined)

Original Trade Receivables:
                                         2025      2024      2023      2022  \
Adani Ports                           4432.36   3666.94   3940.79   2469.68
Asian Paints Ltd                      4313.65   4889.05   4636.94   3871.44
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                     8319.35   5973.86   3458.64   3004.81
Bajaj Finance Ltd                     1416.39   1244.89   1070.21   1017.11
Bharat Electronics Ltd                9116.37   7392.38   7033.48   6108.09
Bharti Airtel Ltd                     7455.70   4727.70   3981.50   4056.20
Eternal Ltd                           1946.00    794.00    456.90    159.90
HCL Technologies Ltd                 25842.00  25521.00  25506.00  20671.00
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                3819.00   2997.00   3079.00   2236.00
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          31158.00  30193.00  25424.00  22698.00
ITC Ltd                               4719.67   4025.82   2956.17   2461.90
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  53713.68  48770.95  44731.53  46138.92
Mahindra and Mahindra Ltd             8279.70   7459.40   7028.02   6373.95
Maruti Suzuki India Ltd               6539.70   4596.80   3301.40   2034.50
NTPC Ltd                             34720.30  33349.68  28825.22  27342.08
Power Grid Corporation of India Ltd   7964.75  11539.63  12961.35   9475.07
Reliance Industries Ltd              42121.00  31628.00  28448.00  23640.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd    13046.11  11249.37  11438.51  10592.89
Tata Motors Ltd                      13248.00  16951.81  15737.97  12442.12
Tata Steel Ltd                        5260.06   6263.53   8257.24  12246.43
Tata Consultancy Services Ltd        59046.00  53577.00  49546.00  34074.00
Tech Mahindra Ltd                    11547.00  11401.10  12881.60  11933.40
Titan Company Ltd                     1068.00   1018.00    674.00    565.00
Trent Ltd                               62.95     81.74     34.39     17.86
UltraTech Cement Ltd                  5890.25   4278.16   3867.02   3071.61

                                         2021      2020      2019      2018  \
Adani Ports                           2925.71   3202.14   2789.66   3537.91
Asian Paints Ltd                      2602.17   1795.22   1907.33   1730.63
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                     2753.07    541.45    370.38    353.02
Bajaj Finance Ltd                      720.10    867.18    805.38  34203.92
Bharat Electronics Ltd                6561.99   6724.02   5373.67   5014.30
Bharti Airtel Ltd                     3637.70   4605.80   4300.60   5883.00
Eternal Ltd                            129.87    123.12     70.34     26.08
HCL Technologies Ltd                 13663.00  14131.00  11706.00   9639.00
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                1758.00   1149.00   1816.00   1310.00
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          19294.00  18487.00  14827.00  13142.00
ITC Ltd                               2501.70   2562.48   4035.28   2682.29
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  42229.78  40731.52  36845.87  34654.08
Mahindra and Mahindra Ltd             6007.76   6928.28   9290.51   8489.82
Maruti Suzuki India Ltd               1279.90   1977.70   2312.80   1465.40
NTPC Ltd                             17718.07  20314.59  12363.52   8812.19
Power Grid Corporation of India Ltd   3675.53   5040.71   4728.10   3640.02
Reliance Industries Ltd              19014.00  19656.00  30089.00  17555.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd     9061.40   9421.24   8884.20   7815.28
Tata Motors Ltd                      12679.08  11172.69  18996.17  19893.30
Tata Steel Ltd                        9539.84   7884.91  11811.00  12415.52
Tata Consultancy Services Ltd        30079.00  30532.00  27346.00  24943.00
Tech Mahindra Ltd                     6472.80   7577.20   6958.60   6497.90
Titan Company Ltd                      366.00    311.55    420.45    295.69
Trent Ltd                               20.77     17.12     16.54     15.10
UltraTech Cement Ltd                  2571.73   2383.22   2787.03   2220.63

                                         2017      2016      2015      2014  \
Adani Ports                           1964.76   2436.09   1287.77   1427.56
Asian Paints Ltd                      1446.60   1186.84   1179.85   1110.28
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                      267.08    177.74      0.93      3.11
Bajaj Finance Ltd                    25654.78      0.00      0.00      0.00
Bharat Electronics Ltd                4368.26   3721.91   3805.32   4155.88
Bharti Airtel Ltd                     4740.20   5503.90   5207.20   6244.10
Eternal Ltd                              0.00      0.00      0.00      0.00
HCL Technologies Ltd                  8301.00   7721.14   6538.69   5682.84
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                1085.00   1264.00   1011.18   1031.09
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          12322.00  11330.00   9713.00   8351.00
ITC Ltd                               2474.29   1917.18   1978.17   2433.55
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  28688.97  26024.98  30089.37  26384.55
Mahindra and Mahindra Ltd             7199.26   5817.60   5476.16   5725.42
Maruti Suzuki India Ltd               1202.60   1323.40   1144.30   1489.10
NTPC Ltd                              8963.89   8288.79   9249.92   6725.66
Power Grid Corporation of India Ltd   3131.93   2739.47   2206.96   1618.29
Reliance Industries Ltd               8177.00   4465.00   5315.00   9411.00
State Bank of India                      0.00      0.00      0.00      0.00
Sun Pharmaceutical Industries Ltd     7202.61   6775.66   5312.32   2200.42
Tata Motors Ltd                      14075.55  13570.91  12579.20  10574.23
Tata Steel Ltd                       11586.82  12066.22  13309.87  16005.77
Tata Consultancy Services Ltd        22617.00  24073.00  20437.94  18230.40
Tech Mahindra Ltd                     5337.70   5770.50   5205.90   4348.60
Titan Company Ltd                      207.60    192.50    189.73    154.13
Trent Ltd                                5.92     12.99     17.69     17.17
UltraTech Cement Ltd                  1757.09   1928.21   1658.82   1632.06

                                         2013
Adani Ports                            728.28
Asian Paints Ltd                       980.88
Axis Bank Ltd                            0.00
Bajaj Finserv Ltd                        0.13
Bajaj Finance Ltd                        0.00
Bharat Electronics Ltd                3363.56
Bharti Airtel Ltd                     6643.00
Eternal Ltd                              0.00
HCL Technologies Ltd                  4497.15
HDFC Bank Ltd                            0.00
Hindustan Unilever Ltd                 996.53
ICICI Bank Ltd                           0.00
Infosys Ltd                           7083.00
ITC Ltd                               1394.23
Kotak Mahindra Bank Ltd                  0.00
Larsen & Toubro Ltd                  23014.91
Mahindra and Mahindra Ltd             5176.97
Maruti Suzuki India Ltd               1489.20
NTPC Ltd                              6096.64
Power Grid Corporation of India Ltd   1491.38
Reliance Industries Ltd               9750.00
State Bank of India                      0.00
Sun Pharmaceutical Industries Ltd     2710.77
Tata Motors Ltd                      10942.66
Tata Steel Ltd                       13993.96
Tata Consultancy Services Ltd        14076.56
Tech Mahindra Ltd                     1703.60
Titan Company Ltd                      165.83
Trent Ltd                               24.42
UltraTech Cement Ltd                  1376.29

Average Trade Receivables:
                                      Avg_2025   Avg_2024   Avg_2023  \
Adani Ports                           4049.650   3803.865   3205.235
Asian Paints Ltd                      4601.350   4762.995   4254.190
Axis Bank Ltd                            0.000      0.000      0.000
Bajaj Finserv Ltd                     7146.605   4716.250   3231.725
Bajaj Finance Ltd                     1330.640   1157.550   1043.660
Bharat Electronics Ltd                8254.375   7212.930   6570.785
Bharti Airtel Ltd                     6091.700   4354.600   4018.850
Eternal Ltd                           1370.000    625.450    308.400
HCL Technologies Ltd                 25681.500  25513.500  23088.500
HDFC Bank Ltd                            0.000      0.000      0.000
Hindustan Unilever Ltd                3408.000   3038.000   2657.500
ICICI Bank Ltd                           0.000      0.000      0.000
Infosys Ltd                          30675.500  27808.500  24061.000
ITC Ltd                               4372.745   3490.995   2709.035
Kotak Mahindra Bank Ltd                  0.000      0.000      0.000
Larsen & Toubro Ltd                  51242.315  46751.240  45435.225
Mahindra and Mahindra Ltd             7869.550   7243.710   6700.985
Maruti Suzuki India Ltd               5568.250   3949.100   2667.950
NTPC Ltd                             34034.990  31087.450  28083.650
Power Grid Corporation of India Ltd   9752.190  12250.490  11218.210
Reliance Industries Ltd              36874.500  30038.000  26044.000
State Bank of India                      0.000      0.000      0.000
Sun Pharmaceutical Industries Ltd    12147.740  11343.940  11015.700
Tata Motors Ltd                      15099.905  16344.890  14090.045
Tata Steel Ltd                        5761.795   7260.385  10251.835
Tata Consultancy Services Ltd        56311.500  51561.500  41810.000
Tech Mahindra Ltd                    11474.050  12141.350  12407.500
Titan Company Ltd                     1043.000    846.000    619.500
Trent Ltd                               72.345     58.065     26.125
UltraTech Cement Ltd                  5084.205   4072.590   3469.315

                                      Avg_2022   Avg_2021   Avg_2020  \
Adani Ports                           2697.695   3063.925   2995.900
Asian Paints Ltd                      3236.805   2198.695   1851.275
Axis Bank Ltd                            0.000      0.000      0.000
Bajaj Finserv Ltd                     2878.940   1647.260    455.915
Bajaj Finance Ltd                      868.605    793.640    836.280
Bharat Electronics Ltd                6335.040   6643.005   6048.845
Bharti Airtel Ltd                     3846.950   4121.750   4453.200
Eternal Ltd                            144.885    126.495     96.730
HCL Technologies Ltd                 17167.000  13897.000  12918.500
HDFC Bank Ltd                            0.000      0.000      0.000
Hindustan Unilever Ltd                1997.000   1453.500   1482.500
ICICI Bank Ltd                           0.000      0.000      0.000
Infosys Ltd                          20996.000  18890.500  16657.000
ITC Ltd                               2481.800   2532.090   3298.880
Kotak Mahindra Bank Ltd                  0.000      0.000      0.000
Larsen & Toubro Ltd                  44184.350  41480.650  38788.695
Mahindra and Mahindra Ltd             6190.855   6468.020   8109.395
Maruti Suzuki India Ltd               1657.200   1628.800   2145.250
NTPC Ltd                             22530.075  19016.330  16339.055
Power Grid Corporation of India Ltd   6575.300   4358.120   4884.405
Reliance Industries Ltd              21327.000  19335.000  24872.500
State Bank of India                      0.000      0.000      0.000
Sun Pharmaceutical Industries Ltd     9827.145   9241.320   9152.720
Tata Motors Ltd                      12560.600  11925.885  15084.430
Tata Steel Ltd                       10893.135   8712.375   9847.955
Tata Consultancy Services Ltd        32076.500  30305.500  28939.000
Tech Mahindra Ltd                     9203.100   7025.000   7267.900
Titan Company Ltd                      465.500    338.775    366.000
Trent Ltd                               19.315     18.945     16.830
UltraTech Cement Ltd                  2821.670   2477.475   2585.125

                                      Avg_2019   Avg_2018   Avg_2017  \
Adani Ports                           3163.785   2751.335   2200.425
Asian Paints Ltd                      1818.980   1588.615   1316.720
Axis Bank Ltd                            0.000      0.000      0.000
Bajaj Finserv Ltd                      361.700    310.050    222.410
Bajaj Finance Ltd                    17504.650  29929.350  12827.390
Bharat Electronics Ltd                5193.985   4691.280   4045.085
Bharti Airtel Ltd                     5091.800   5311.600   5122.050
Eternal Ltd                             48.210     13.040      0.000
HCL Technologies Ltd                 10672.500   8970.000   8011.070
HDFC Bank Ltd                            0.000      0.000      0.000
Hindustan Unilever Ltd                1563.000   1197.500   1174.500
ICICI Bank Ltd                           0.000      0.000      0.000
Infosys Ltd                          13984.500  12732.000  11826.000
ITC Ltd                               3358.785   2578.290   2195.735
Kotak Mahindra Bank Ltd                  0.000      0.000      0.000
Larsen & Toubro Ltd                  35749.975  31671.525  27356.975
Mahindra and Mahindra Ltd             8890.165   7844.540   6508.430
Maruti Suzuki India Ltd               1889.100   1334.000   1263.000
NTPC Ltd                             10587.855   8888.040   8626.340
Power Grid Corporation of India Ltd   4184.060   3385.975   2935.700
Reliance Industries Ltd              23822.000  12866.000   6321.000
State Bank of India                      0.000      0.000      0.000
Sun Pharmaceutical Industries Ltd     8349.740   7508.945   6989.135
Tata Motors Ltd                      19444.735  16984.425  13823.230
Tata Steel Ltd                       12113.260  12001.170  11826.520
Tata Consultancy Services Ltd        26144.500  23780.000  23345.000
Tech Mahindra Ltd                     6728.250   5917.800   5554.100
Titan Company Ltd                      358.070    251.645    200.050
Trent Ltd                               15.820     10.510      9.455
UltraTech Cement Ltd                  2503.830   1988.860   1842.650

                                      Avg_2016   Avg_2015   Avg_2014  \
Adani Ports                           1861.930   1357.665   1077.920
Asian Paints Ltd                      1183.345   1145.065   1045.580
Axis Bank Ltd                            0.000      0.000      0.000
Bajaj Finserv Ltd                       89.335      2.020      1.620
Bajaj Finance Ltd                        0.000      0.000      0.000
Bharat Electronics Ltd                3763.615   3980.600   3759.720
Bharti Airtel Ltd                     5355.550   5725.650   6443.550
Eternal Ltd                              0.000      0.000      0.000
HCL Technologies Ltd                  7129.915   6110.765   5089.995
HDFC Bank Ltd                            0.000      0.000      0.000
Hindustan Unilever Ltd                1137.590   1021.135   1013.810
ICICI Bank Ltd                           0.000      0.000      0.000
Infosys Ltd                          10521.500   9032.000   7717.000
ITC Ltd                               1947.675   2205.860   1913.890
Kotak Mahindra Bank Ltd                  0.000      0.000      0.000
Larsen & Toubro Ltd                  28057.175  28236.960  24699.730
Mahindra and Mahindra Ltd             5646.880   5600.790   5451.195
Maruti Suzuki India Ltd               1233.850   1316.700   1489.150
NTPC Ltd                              8769.355   7987.790   6411.150
Power Grid Corporation of India Ltd   2473.215   1912.625   1554.835
Reliance Industries Ltd               4890.000   7363.000   9580.500
State Bank of India                      0.000      0.000      0.000
Sun Pharmaceutical Industries Ltd     6043.990   3756.370   2455.595
Tata Motors Ltd                      13075.055  11576.715  10758.445
Tata Steel Ltd                       12688.045  14657.820  14999.865
Tata Consultancy Services Ltd        22255.470  19334.170  16153.480
Tech Mahindra Ltd                     5488.200   4777.250   3026.100
Titan Company Ltd                      191.115    171.930    159.980
Trent Ltd                               15.340     17.430     20.795
UltraTech Cement Ltd                  1793.515   1645.440   1504.175

                                      Avg_2013
Adani Ports                            364.140
Asian Paints Ltd                       490.440
Axis Bank Ltd                            0.000
Bajaj Finserv Ltd                        0.065
Bajaj Finance Ltd                        0.000
Bharat Electronics Ltd                1681.780
Bharti Airtel Ltd                     3321.500
Eternal Ltd                              0.000
HCL Technologies Ltd                  2248.575
HDFC Bank Ltd                            0.000
Hindustan Unilever Ltd                 498.265
ICICI Bank Ltd                           0.000
Infosys Ltd                           3541.500
ITC Ltd                                697.115
Kotak Mahindra Bank Ltd                  0.000
Larsen & Toubro Ltd                  11507.455
Mahindra and Mahindra Ltd             2588.485
Maruti Suzuki India Ltd                744.600
NTPC Ltd                              3048.320
Power Grid Corporation of India Ltd    745.690
Reliance Industries Ltd               4875.000
State Bank of India                      0.000
Sun Pharmaceutical Industries Ltd     1355.385
Tata Motors Ltd                       5471.330
Tata Steel Ltd                        6996.980
Tata Consultancy Services Ltd         7038.280
Tech Mahindra Ltd                      851.800
Titan Company Ltd                       82.915
Trent Ltd                               12.210
UltraTech Cement Ltd                   688.145

Combined DataFrame (Original + Average):
                                         2025      2024      2023      2022  \
Adani Ports                           4432.36   3666.94   3940.79   2469.68
Asian Paints Ltd                      4313.65   4889.05   4636.94   3871.44
Axis Bank Ltd                            0.00      0.00      0.00      0.00
Bajaj Finserv Ltd                     8319.35   5973.86   3458.64   3004.81
Bajaj Finance Ltd                     1416.39   1244.89   1070.21   1017.11
Bharat Electronics Ltd                9116.37   7392.38   7033.48   6108.09
Bharti Airtel Ltd                     7455.70   4727.70   3981.50   4056.20
Eternal Ltd                           1946.00    794.00    456.90    159.90
HCL Technologies Ltd                 25842.00  25521.00  25506.00  20671.00
HDFC Bank Ltd                            0.00      0.00      0.00      0.00
Hindustan Unilever Ltd                3819.00   2997.00   3079.00   2236.00
ICICI Bank Ltd                           0.00      0.00      0.00      0.00
Infosys Ltd                          31158.00  30193.00  25424.00  22698.00
ITC Ltd                               4719.67   4025.82   2956.17   2461.90
Kotak Mahindra Bank Ltd                  0.00      0.00      0.00      0.00
Larsen & Toubro Ltd                  53713.68  48770.95  44731.53  46138.92

In [12]:
tr.shape

(30, 13)

In [6]:
avg_tr.to_csv('Average_Trade_Receivables.csv', index=True)

In [13]:
avg_tr.shape

(30, 13)

In [5]:
rf=pd.read_csv('Revenue_From_Operations.csv')
rf

,Unnamed: 0,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
0,Adani Ports,30475.33,26710.56,20617.64,15795.81,12425.50,11201.67,10780.98,11314.75,8427.35,7102.50,6151.98,4823.99,3576.63
1,Asian Paints Ltd,33797.36,35382.12,34367.83,28923.48,21485.20,20048.32,19062.38,16600.58,14872.52,14091.56,14005.33,12581.64,10906.01
2,Axis Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,Bajaj Finserv Ltd,133821.05,110381.91,82071.24,68406.08,60591.20,54346.69,42604.00,32862.37,21149.64,8563.42,6471.24,4908.01,3821.09
4,Bajaj Finance Ltd,68264.59,53945.36,40288.71,30739.15,26504.52,26223.07,18397.29,12336.56,9258.03,6956.59,5119.97,0.00,0.00
5,Bharat Electronics Ltd,23117.30,19905.49,17404.18,15084.74,13849.71,12636.58,11854.70,10068.72,8336.58,7198.66,6895.32,6335.86,6151.14
6,Bharti Airtel Ltd,172985.20,149982.40,139144.80,116546.90,100615.80,87539.00,80780.20,83687.90,95468.30,96532.10,96100.70,85746.10,80311.20
7,Eternal Ltd,20243.00,12114.00,7079.40,4119.60,1915.75,2398.40,1296.30,466.36,0.00,0.00,0.00,0.00,0.00
8,HCL Technologies Ltd,117055.00,109913.00,101456.00,85651.00,75379.00,70676.00,60427.00,50569.00,47568.00,31135.94,36701.22,32143.66,25581.06
9,HDFC Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,Hindustan Unilever Ltd,62288.00,60966.00,59549.00,51548.00,46321.00,39238.00,38684.00,34878.00,32464.00,31461.00,31199.72,28538.98,26317.15
11,ICICI Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12,Infosys Ltd,162990.00,153670.00,146767.00,121641.00,100472.00,90791.00,82675.00,70522.00,68484.00,62441.00,53319.00,50133.00,40352.00
13,ITC Ltd,74653.32,70315.49,70245.22,60081.36,48952.81,48979.08,47839.00,43122.90,42360.04,38804.19,38433.31,34984.70,31323.45
14,Kotak Mahindra Bank Ltd,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15,Larsen & Toubro Ltd,254208.65,221112.91,181661.42,155672.46,134476.75,144308.05,133342.20,117908.12,107887.53,100034.24,89589.68,84429.34,74498.00
16,Mahindra and Mahindra Ltd,155645.26,135803.03,119040.38,89353.96,72678.98,74304.07,103015.23,90770.68,82069.37,74762.30,63862.55,66930.97,62643.54
17,Maruti Suzuki India Ltd,145109.90,134921.70,112511.30,83799.80,66571.80,71704.80,83038.50,78117.10,66924.70,56452.80,49295.00,43271.80,43215.90
18,NTPC Ltd,186144.66,176641.71,173985.61,132669.28,111267.88,109078.63,99615.00,86118.25,81193.50,72839.14,80034.89,78538.05,68891.48
19,Power Grid Corporation of India Ltd,44072.92,44202.75,44005.22,40784.69,39300.83,36800.13,34831.17,29904.96,25478.82,20576.04,17658.51,15597.89,13115.50
20,Reliance Industries Ltd,964693.00,901064.00,877835.00,699962.00,466924.00,597535.00,569209.00,391677.00,305382.00,273999.00,375435.00,434460.00,397062.00
21,State Bank of India,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
22,Sun Pharmaceutical Industries Ltd,52041.25,47758.45,43278.87,38426.42,33139.18,32325.17,28686.28,25992.02,29993.93,27888.07,27286.50,16004.39,11238.89
23,Tata Motors Ltd,436821.00,434984.12,342874.58,275235.23,246972.17,258594.36,299190.59,288596.09,265498.47,269560.11,260734.33,230677.10,187652.84
24,Tata Steel Ltd,216840.35,227296.20,241636.25,242326.87,154719.28,146106.00,154691.63,130880.87,111562.05,105683.18,138318.91,147347.28,133416.60
25,Tata Consultancy Services Ltd,255324.00,240893.00,225458.00,191754.00,164177.00,156949.00,146463.00,123104.00,117966.00,108646.00,94648.41,81809.36,62989.48
26,Tech Mahindra Ltd,52988.30,51995.50,53290.20,44646.00,37855.10,36867.70,34742.10,30772.90,29140.80,26494.20,22621.30,18831.40,6873.10
27,Titan Company Ltd,57143.00,46751.00,37924.00,27417.00,20088.00,20767.70,19592.06,15946.49,13186.78,11187.74,11800.99,10826.15,10019.35
28,Trent Ltd,16873.72,12205.31,8112.33,4417.27,2546.90,3441.31,2585.75,2123.01,1779.99,1540.90,2236.77,2272.32,2017.28
29,UltraTech Cement Ltd,70857.27,67535.73,60462.60,49729.38,42677.00,41780.55,40903.81,30541.18,25091.62,24879.85,24064.75,21443.72,21156.12

In [14]:
rf.shape

(30, 13)

In [7]:
av=pd.read_csv('Average_Trade_Receivables.csv')
av

,Unnamed: 0,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
0,Adani Ports,4049.650,3803.865,3205.235,2697.695,3063.925,2995.900,3163.785,2751.335,2200.425,1861.930,1357.665,1077.920,364.140
1,Asian Paints Ltd,4601.350,4762.995,4254.190,3236.805,2198.695,1851.275,1818.980,1588.615,1316.720,1183.345,1145.065,1045.580,490.440
2,Axis Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,Bajaj Finserv Ltd,7146.605,4716.250,3231.725,2878.940,1647.260,455.915,361.700,310.050,222.410,89.335,2.020,1.620,0.065
4,Bajaj Finance Ltd,1330.640,1157.550,1043.660,868.605,793.640,836.280,17504.650,29929.350,12827.390,0.000,0.000,0.000,0.000
5,Bharat Electronics Ltd,8254.375,7212.930,6570.785,6335.040,6643.005,6048.845,5193.985,4691.280,4045.085,3763.615,3980.600,3759.720,1681.780
6,Bharti Airtel Ltd,6091.700,4354.600,4018.850,3846.950,4121.750,4453.200,5091.800,5311.600,5122.050,5355.550,5725.650,6443.550,3321.500
7,Eternal Ltd,1370.000,625.450,308.400,144.885,126.495,96.730,48.210,13.040,0.000,0.000,0.000,0.000,0.000
8,HCL Technologies Ltd,25681.500,25513.500,23088.500,17167.000,13897.000,12918.500,10672.500,8970.000,8011.070,7129.915,6110.765,5089.995,2248.575
9,HDFC Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
10,Hindustan Unilever Ltd,3408.000,3038.000,2657.500,1997.000,1453.500,1482.500,1563.000,1197.500,1174.500,1137.590,1021.135,1013.810,498.265
11,ICICI Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
12,Infosys Ltd,30675.500,27808.500,24061.000,20996.000,18890.500,16657.000,13984.500,12732.000,11826.000,10521.500,9032.000,7717.000,3541.500
13,ITC Ltd,4372.745,3490.995,2709.035,2481.800,2532.090,3298.880,3358.785,2578.290,2195.735,1947.675,2205.860,1913.890,697.115
14,Kotak Mahindra Bank Ltd,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
15,Larsen & Toubro Ltd,51242.315,46751.240,45435.225,44184.350,41480.650,38788.695,35749.975,31671.525,27356.975,28057.175,28236.960,24699.730,11507.455
16,Mahindra and Mahindra Ltd,7869.550,7243.710,6700.985,6190.855,6468.020,8109.395,8890.165,7844.540,6508.430,5646.880,5600.790,5451.195,2588.485
17,Maruti Suzuki India Ltd,5568.250,3949.100,2667.950,1657.200,1628.800,2145.250,1889.100,1334.000,1263.000,1233.850,1316.700,1489.150,744.600
18,NTPC Ltd,34034.990,31087.450,28083.650,22530.075,19016.330,16339.055,10587.855,8888.040,8626.340,8769.355,7987.790,6411.150,3048.320
19,Power Grid Corporation of India Ltd,9752.190,12250.490,11218.210,6575.300,4358.120,4884.405,4184.060,3385.975,2935.700,2473.215,1912.625,1554.835,745.690
20,Reliance Industries Ltd,36874.500,30038.000,26044.000,21327.000,19335.000,24872.500,23822.000,12866.000,6321.000,4890.000,7363.000,9580.500,4875.000
21,State Bank of India,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22,Sun Pharmaceutical Industries Ltd,12147.740,11343.940,11015.700,9827.145,9241.320,9152.720,8349.740,7508.945,6989.135,6043.990,3756.370,2455.595,1355.385
23,Tata Motors Ltd,15099.905,16344.890,14090.045,12560.600,11925.885,15084.430,19444.735,16984.425,13823.230,13075.055,11576.715,10758.445,5471.330
24,Tata Steel Ltd,5761.795,7260.385,10251.835,10893.135,8712.375,9847.955,12113.260,12001.170,11826.520,12688.045,14657.820,14999.865,6996.980
25,Tata Consultancy Services Ltd,56311.500,51561.500,41810.000,32076.500,30305.500,28939.000,26144.500,23780.000,23345.000,22255.470,19334.170,16153.480,7038.280
26,Tech Mahindra Ltd,11474.050,12141.350,12407.500,9203.100,7025.000,7267.900,6728.250,5917.800,5554.100,5488.200,4777.250,3026.100,851.800
27,Titan Company Ltd,1043.000,846.000,619.500,465.500,338.775,366.000,358.070,251.645,200.050,191.115,171.930,159.980,82.915
28,Trent Ltd,72.345,58.065,26.125,19.315,18.945,16.830,15.820,10.510,9.455,15.340,17.430,20.795,12.210
29,UltraTech Cement Ltd,5084.205,4072.590,3469.315,2821.670,2477.475,2585.125,2503.830,1988.860,1842.650,1793.515,1645.440,1504.175,688.145

In [15]:
av.shape

(30, 13)

In [16]:
rf.drop(columns=['Unnamed: 0'], inplace=True)
av.drop(columns=['Unnamed: 0'], inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [17]:
atp=rf/av
atp

,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
0,7.525423,7.021953,6.432489,5.855299,4.055419,3.739000,3.407621,4.112458,3.829874,3.814590,4.531295,4.475276,9.822129
1,7.345097,7.428544,8.078584,8.935812,9.771796,10.829466,10.479708,10.449719,11.295127,11.908243,12.231035,12.033168,22.237195
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18.725122,23.404593,25.395490,23.760856,36.783022,119.203558,117.788222,105.990550,95.093026,95.857391,3203.584158,3029.635802,58786.000000
4,51.302073,46.603050,38.603290,35.389101,33.396149,31.356806,1.050994,0.412189,0.721739,inf,inf,NaN,NaN
5,2.800612,2.759695,2.648722,2.381159,2.084856,2.089090,2.282390,2.146263,2.060916,1.912698,1.732231,1.685195,3.657518
6,28.396868,34.442291,34.623039,30.295923,24.410942,19.657550,15.864763,15.755686,18.638690,18.024685,16.784243,13.307276,24.179196
7,14.775912,19.368455,22.955253,28.433585,15.144867,24.794790,26.888612,35.763804,NaN,NaN,NaN,NaN,NaN
8,4.557950,4.308033,4.394222,4.989282,5.424120,5.470914,5.661935,5.637570,5.937784,4.366944,6.005994,6.315067,11.376565
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,18.276995,20.067808,22.407902,25.812719,31.868593,26.467454,24.749840,29.125678,27.640698,27.655834,30.553962,28.150225,52.817577
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,5.313361,5.526008,6.099788,5.793532,5.318652,5.450621,5.911902,5.538957,5.790969,5.934610,5.903344,6.496436,11.394042
13,17.072416,20.141962,25.929979,24.208784,19.332966,14.847184,14.242948,16.725388,19.291964,19.923339,17.423277,18.279368,44.932974
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,4.960913,4.729562,3.998251,3.523249,3.241915,3.720364,3.729854,3.722843,3.943694,3.565371,3.172781,3.418229,6.473890
16,19.778165,18.747718,17.764609,14.433218,11.236666,9.162714,11.587550,11.571192,12.609703,13.239577,11.402418,12.278220,24.200851
17,26.060234,34.165177,42.171442,50.567101,40.871685,33.424916,43.956646,58.558546,52.988678,45.753374,37.438293,29.058053,58.039081
18,5.469214,5.682091,6.195263,5.888541,5.851175,6.675945,9.408421,9.689228,9.412277,8.306100,10.019654,12.250228,22.599819
19,4.519284,3.608243,3.922660,6.202712,9.017840,7.534209,8.324730,8.832009,8.678959,8.319552,9.232604,10.031862,17.588408
20,26.161521,29.997470,33.705844,32.820462,24.149160,24.023922,23.894257,30.442795,48.312292,56.032515,50.989406,45.348364,81.448615
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4.284027,4.210041,3.928835,3.910232,3.585979,3.531756,3.435590,3.461474,4.291508,4.614182,7.264061,6.517520,8.292028
23,28.928725,26.612851,24.334527,21.912586,20.708918,17.143131,15.386715,16.991808,19.206688,20.616365,22.522307,21.441491,34.297482
24,37.634166,31.306356,23.570049,22.245834,17.758565,14.836177,12.770438,10.905676,9.433210,8.329351,9.436527,9.823240,19.067741
25,4.534136,4.671955,5.392442,5.978021,5.417399,5.423442,5.602058,5.176787,5.053159,4.881766,4.895396,5.064504,8.949556
26,4.618099,4.282514,4.294999,4.851191,5.388626,5.072676,5.163616,5.200057,5.246719,4.827484,4.735214,6.222993,8.068913
27,54.787152,55.261229,61.217111,58.897959,59.295993,56.742350,54.715726,63.368992,65.917421,58.539309,68.638341,67.671896,120.838811
28,233.239616,210.200809,310.519809,228.696350,134.436527,204.474747,163.448167,201.999049,188.259122,100.449804,128.328744,109.272421,165.215397
29,13.936745,16.582993,17.427821,17.624095,17.226006,16.161907,16.336496,15.356124,13.617138,13.872117,14.625115,14.256134,30.743695

In [18]:
atp.to_csv('AToP.csv', index=True)

PermissionError: [Errno 13] Permission denied: 'AToP.csv'